In [1]:
import pandas as pd
import numpy as np
import cx_Oracle
import os
import json
import datetime
import warnings
import matplotlib.pyplot as plt
warnings.filterwarnings(action="ignore")
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By
import bs4
import requests
import time
import math
import random
from shapely.geometry import Point, Polygon
import time as timesys
from pyproj import Geod
from haversine import haversine
pd.set_option('display.max_columns', None)

In [2]:
interpolation_number = "10000"

In [3]:
COSCO_FOS_voyages_list = [
    'COSCO_FOS_VRKR6_2022_20processed', 'COSCO_FOS_VRKR6_2022_23processed',
    'COSCO_FOS_VRKR6_2022_24processed', 'COSCO_FOS_VRKR6_2022_25processed',
    'COSCO_FOS_VRKR6_2022_26processed', 'COSCO_FOS_VRKR6_2022_27processed',
    'COSCO_FOS_VRKR6_2022_28processed', 'COSCO_FOS_VRKR6_2022_29processed',
    'COSCO_FOS_VRKR6_2022_30processed'
]

# 전항지 출항 확인

전항지 출항 지점 확인

In [4]:
import os
 
path_dir = 'voy_path'
 
file_list = os.listdir(path_dir)
file_new_list = []
for i in file_list:
    if "portmis" in i:
        file_new_list.append(i)

In [5]:
# ATA 확인
def check_ATA(df_test):
    for i in df_test.index:
        LONGITUDE = df_test.loc[i, 'longitude']
        LATITUDE = df_test.loc[i, 'latitude']
        if Point(LONGITUDE, LATITUDE).within(poly_busan):    
            stop_index = i - 1
            break
            continue
    return stop_index

# 시각화 툴로 processed된 것들 확인

항로 클러스터링

In [6]:
# dense_upper_china_list = ['COSCO_FOS_VRKR6_23processed'
# ,'AKA_BHUM_9V7282_7processed'
# , 'COSCO_FOS_VRKR6_25processed'
# , 'MSC_LA_SPEZIA_DIGX2_2processed'
# , 'OOCL_NEW_YORK_VRJS2_2processed'
# , 'MSC_WASHINGTON_5LDP4_4processed'
# , 'MSC_SOFIA_PAZ_D5FL9_2processed'
# , 'ZHU_CHENG_XIN_ZHOU_VRKR6_26processed'
# , 'OOCL_HAMBURG_VRZK9_6processed'
# , 'SEAMAX_STRATFORD_V7EP2_6processed'
# , 'OOCL_LUXEMBOURG_VRGO3_5processed'
# , 'ZHU_CHENG_XIN_ZHOU_VRKR6_25processed'
# , 'MSC_LUCIANA_3FTY3_4processed'
# , 'MSC_RENEE_VRPL2_5processed'
# , 'COSCO_FOS_VRKR6_24processed'
# , 'COSCO_FOS_VRKR6_20processed'
# , 'COSCO_FOS_VRKR6_26processed'
# , 'ZHU_CHENG_XIN_ZHOU_VRKR6_23processed'
# , 'OOCL_HAMBURG_VRZK9_5processed']

COSCO_FOS_voyages_list = [
    'COSCO_FOS_VRKR6_2022_20processed', 'COSCO_FOS_VRKR6_2022_23processed',
    'COSCO_FOS_VRKR6_2022_24processed', 'COSCO_FOS_VRKR6_2022_25processed',
    'COSCO_FOS_VRKR6_2022_26processed', 'COSCO_FOS_VRKR6_2022_27processed',
    'COSCO_FOS_VRKR6_2022_28processed', 'COSCO_FOS_VRKR6_2022_29processed',
    'COSCO_FOS_VRKR6_2022_30processed'
]

AKA_BHUM_voyages_list = [
    'AKA_BHUM_9V7282_2022_7processed', 'AKA_BHUM_9V7282_2022_8processed'
]
OOCL_NEW_YORK_voyages_list = [
    'OOCL_NEW_YORK_VRJS2_2022_1processed',
    'OOCL_NEW_YORK_VRJS2_2022_2processed',
    'OOCL_NEW_YORK_VRJS2_2022_3processed'
]

OOCL_LUXEMBOURG_voyages_list = [
    'OOCL_LUXEMBOURG_VRGO3_2022_5processed',
    'OOCL_LUXEMBOURG_VRGO3_2022_6processed'
]

OOCL_GENOA_voyages_list = [
    'OOCL_GENOA_VROK9_2022_3processed', 'OOCL_GENOA_VROK9_2022_5processed'
]

OOCL_HAMBURG_voyages_list = [
    'OOCL_HAMBURG_VRZK9_2022_5processed', 'OOCL_HAMBURG_VRZK9_2022_6processed'
]

SEAMAX_STRATFORD_voyages_list = [
    'SEAMAX_STRATFORD_V7EP2_2022_6processed',
    'SEAMAX_STRATFORD_V7EP2_2022_7processed'
]

ZIM_CHARLESTORN_voyages_list = [
    'ZIM_CHARLESTON_VRUC3_2022_6processed',
    'ZIM_CHARLESTON_VRUC3_2022_7processed'
]

single_voyage_list = [
    'MSC_ARIANE_3FDA3_2022_1processed', 'MSC_DANIT_3FZU8_2022_2processed',
    'MSC_EVA_3EVM7_2022_1processed', 'MSC_EXPRESS_III_A8LG7_2022_1processed',
    'MSC_KANOKO_D5TM3_2023_1processed', 'MSC_LA_SPEZIA_DIGX2_2022_2processed',
    'MSC_VANESSA_HOWD_2023_1processed', 'MSC_VIRGO_CQEB9_2023_2processed',
    'MSC_SOFIA_PAZ_D5FL9_2022_2processed',
    'MSC_WASHINGTON_5LDP4_2022_4processed',
    'MSC_RAVENNA_A8ZU8_2022_3processed', 'MSC_VANDYA_3FDW4_2022_2processed',
    'MSC_RENEE_VRPL2_2022_5processed', 'SEASPAN_OCEANIA_VRBI2_2023_1processed',
    'SEASPAN_BREEZE_VRNL8_2023_1processed', 'VALENCE_9HA3398_2023_1processed'
]

In [7]:
upper_china_path_dir = 'voy_path/upper_china/processed/'

# Tianjin to Busan PNIT

## COSCO_FOS

In [8]:
coordinates_array = pd.DataFrame(data={"latitude" : [],"longitude" : []})

for i in COSCO_FOS_voyages_list:
    df = pd.read_csv(upper_china_path_dir + i + ".csv")
    coordinates_array = coordinates_array.append(df[["latitude","longitude"]], ignore_index=True)

In [9]:
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
from shapely.geometry import LineString

In [11]:
from scipy import interpolate
import pandas as pd

## below 3 knot 제거

### interpolation 10000

In [12]:
max_speed_list = []
min_speed_list = []
for i in COSCO_FOS_voyages_list:
    df = pd.read_csv(upper_china_path_dir + i + ".csv")
    data = df
    min_speed = data["speed"].min()
    max_speed = data["speed"].max()
    max_speed_list.append(max_speed)
    min_speed_list.append(min_speed)
min_speed = np.min(min_speed_list)
max_speed = np.max(max_speed_list)

# norm = plt.Normalize(min_speed, max_speed)
# cmap = plt.get_cmap('RdYlGn')
# sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
# Create a ScalarMappable with the colormap and normalization

mean_speed_dict = {"voyage" : [],"mean_speed" : []}

for i in COSCO_FOS_voyages_list:
#     fig, ax = plt.subplots()
    
    df = pd.read_csv(upper_china_path_dir + i + ".csv")
    data = df
    # 3노트 이하 데이터 삭제
    data = data[data["speed"] >= 3]
    data.reset_index(inplace=True, drop=True)
#     min_speed = data["speed"].min()
#     max_speed = data["speed"].max()
    vessel_name = data["vessel_name"].values[0]
    voyage_name = i.split('processed')[0]
    speed_std = data["speed"].std()
    
    
    
    data['timestamp'] = pd.to_datetime(data['timestamp'])
    data['timestamp_seconds'] = (data['timestamp'] - pd.Timestamp("1970-01-01")) / pd.Timedelta(seconds=1)

    # Create a function that performs the interpolation
    interp_longitude = interpolate.interp1d(data['timestamp_seconds'], data['longitude'])
    interp_latitude = interpolate.interp1d(data['timestamp_seconds'], data['latitude'])
    interp_speed = interpolate.interp1d(data['timestamp_seconds'], data['speed'])

    # Specify the range of new x values for the interpolation
    new_x = np.linspace(data['timestamp_seconds'].min(), data['timestamp_seconds'].max(), num=int(interpolation_number))

    # Use the interpolation function to estimate y values for the new x values
    interp_longitude_y = interp_longitude(new_x)
    interp_latitude_y = interp_latitude(new_x)
    interp_speed_y = interp_speed(new_x)
    # Create new DataFrame with the interpolated values
    interp_data = pd.DataFrame({'timestamp': new_x, 'longitude': interp_longitude_y, 'latitude': interp_latitude_y, 'speed': interp_speed_y})
#     i = i.split("processed")[0]
    interp_data.to_csv(upper_china_path_dir + 'interpolated/'+ f"interpolated_{i}_below_3knot_{interpolation_number}.csv", encoding="utf-8 sig", header=True, index=False)
    
    # plot the data
#     sc = ax.scatter(interp_data['longitude'], interp_data['latitude'],c = interp_data['speed'], cmap = cmap, norm = norm, s=0.1)

    # Add axis labels
#     ax.set_xlabel('Longitude')
#     ax.set_ylabel('Latitude')
#     ax.set_title(f"{vessel_name}_{voyage_name}")
#     # Add a colorbar
#     cbar = plt.colorbar(sc,label='Speed')

        # Show the plot
#     plt.show()
        
    check = data["speed"].apply(lambda x : True if x < 3 else False)
    s = data.drop(data[check].index)["speed"]
    print(f"보간법 전 일반 평균 속도 : {data['speed'].mean()}")
    print(f"보간법 전 일반 속도 표준편차: {data['speed'].std()}")
    print(f"보간법 전 저속 제거 평균 속도 : {s.mean()}")
    print(f'보간법 전 저속 제거 속도 표준편차: {s.std()}')
    print('-')
    check = interp_data["speed"].apply(lambda x : True if x < 3 else False)
    s = interp_data.drop(interp_data[check].index)["speed"]
    print(f"보간법 후 일반 평균 속도 : {interp_data['speed'].mean()}")
    print(f"보간법 후 일반 속도 표준편차: {interp_data['speed'].std()}")
    print(f"보간법 후 저속 제거 평균 속도 : {s.mean()}")
    mean_speed_dict['voyage'].append(voyage_name)
    mean_speed_dict['mean_speed'].append(s.mean())
    print(f'보간법 후 저속 제거 속도 표준편차: {s.std()}')

보간법 전 일반 평균 속도 : 10.84341085271318
보간법 전 일반 속도 표준편차: 2.994517557558759
보간법 전 저속 제거 평균 속도 : 10.84341085271318
보간법 전 저속 제거 속도 표준편차: 2.994517557558759
-
보간법 후 일반 평균 속도 : 9.502855954045097
보간법 후 일반 속도 표준편차: 3.3838226026451164
보간법 후 저속 제거 평균 속도 : 9.502855954045097
보간법 후 저속 제거 속도 표준편차: 3.3838226026451164
보간법 전 일반 평균 속도 : 16.75807860262009
보간법 전 일반 속도 표준편차: 2.649105009334675
보간법 전 저속 제거 평균 속도 : 16.75807860262009
보간법 전 저속 제거 속도 표준편차: 2.649105009334675
-
보간법 후 일반 평균 속도 : 17.240594055461848
보간법 후 일반 속도 표준편차: 2.2227170921887347
보간법 후 저속 제거 평균 속도 : 17.240594055461848
보간법 후 저속 제거 속도 표준편차: 2.2227170921887347
보간법 전 일반 평균 속도 : 12.309897610921503
보간법 전 일반 속도 표준편차: 1.9405006816493167
보간법 전 저속 제거 평균 속도 : 12.309897610921503
보간법 전 저속 제거 속도 표준편차: 1.9405006816493167
-
보간법 후 일반 평균 속도 : 12.66388142216077
보간법 후 일반 속도 표준편차: 1.7173707764247432
보간법 후 저속 제거 평균 속도 : 12.66388142216077
보간법 후 저속 제거 속도 표준편차: 1.7173707764247432
보간법 전 일반 평균 속도 : 17.315503875968993
보간법 전 일반 속도 표준편차: 2.7140332760836965
보간법 전 저속 제거 평균 속도 : 17.315503875968993
보간법 전 저속 제거 속도 표준편차: 2.7140332760836965
-
보간법 후 일반 평균 속도 : 17.848733299065696
보간법 후 일반 속도 표준편차: 2.3216393176047143
보간법 후 저속 제거 평균 속도 : 17.848733299065696
보간법 후 저속 제거 속도 표준편차: 2.3216393176047143
보간법 전 일반 평균 속도 : 16.46241379310345
보간법 전 일반 속도 표준편차: 1.9907734589655557
보간법 전 저속 제거 평균 속도 : 16.46241379310345
보간법 전 저속 제거 속도 표준편차: 1.9907734589655557
-
보간법 후 일반 평균 속도 : 16.841980107657207
보간법 후 일반 속도 표준편차: 2.2189569194214553
보간법 후 저속 제거 평균 속도 : 16.841980107657207
보간법 후 저속 제거 속도 표준편차: 2.2189569194214553
보간법 전 일반 평균 속도 : 14.273705179282867
보간법 전 일반 속도 표준편차: 3.0860761197243773
보간법 전 저속 제거 평균 속도 : 14.273705179282867
보간법 전 저속 제거 속도 표준편차: 3.0860761197243773
-
보간법 후 일반 평균 속도 : 15.56333595131496
보간법 후 일반 속도 표준편차: 2.9921050738882284
보간법 후 저속 제거 평균 속도 : 15.56333595131496
보간법 후 저속 제거 속도 표준편차: 2.9921050738882284
보간법 전 일반 평균 속도 : 10.858545454545455
보간법 전 일반 속도 표준편차: 2.3006087881871635
보간법 전 저속 제거 평균 속도 : 10.858545454545455
보간법 전 저속 제거 속도 표준편차: 2.3006087881871635
-
보간법 후 일반 평균 속도 : 11.193688715595577
보간법 후 일반 속도 표준편차: 2.716019361373682
보간법 후 저속 제거 평균 속도 : 11.193688715595577
보간법 후 저속 제거 속도 표준편차: 2.716019361373682
보간법 전 일반 평균 속도 : 11.938951310861425
보간법 전 일반 속도 표준편차: 2.695788212023827
보간법 전 저속 제거 평균 속도 : 11.938951310861425
보간법 전 저속 제거 속도 표준편차: 2.695788212023827
-
보간법 후 일반 평균 속도 : 12.983241007679503
보간법 후 일반 속도 표준편차: 2.5470938935237695
보간법 후 저속 제거 평균 속도 : 12.983241007679503
보간법 후 저속 제거 속도 표준편차: 2.5470938935237695
보간법 전 일반 평균 속도 : 10.505362776025237
보간법 전 일반 속도 표준편차: 2.8900094626015407
보간법 전 저속 제거 평균 속도 : 10.505362776025237
보간법 전 저속 제거 속도 표준편차: 2.8900094626015407
-
보간법 후 일반 평균 속도 : 9.613636220424095
보간법 후 일반 속도 표준편차: 3.649020055411645
보간법 후 저속 제거 평균 속도 : 9.613636220424095
보간법 후 저속 제거 속도 표준편차: 3.649020055411645

In [13]:
mean_speed_df = pd.DataFrame(mean_speed_dict)
list(mean_speed_df[mean_speed_df["mean_speed"] < 14].voyage)

['COSCO_FOS_VRKR6_2022_20',
 'COSCO_FOS_VRKR6_2022_24',
 'COSCO_FOS_VRKR6_2022_28',
 'COSCO_FOS_VRKR6_2022_29',
 'COSCO_FOS_VRKR6_2022_30']

In [14]:
list(mean_speed_df[mean_speed_df["mean_speed"] > 14].voyage)

['COSCO_FOS_VRKR6_2022_23',
 'COSCO_FOS_VRKR6_2022_25',
 'COSCO_FOS_VRKR6_2022_26',
 'COSCO_FOS_VRKR6_2022_27']

## high speed 항차 : 23,25, 26,27

In [15]:
high_speed_path_data =[]
low_speed_path_data =[]
for i in COSCO_FOS_voyages_list:
    i = i.split("processed")[0]
    if i in list(mean_speed_df[mean_speed_df["mean_speed"] < 14].voyage):
        i = "interpolated/interpolated_" + i + f'processed_below_3knot_{interpolation_number}'
        df = pd.read_csv(upper_china_path_dir + i + ".csv")
        low_speed_path_data.append(df)
    elif i in list(mean_speed_df[mean_speed_df["mean_speed"] >= 14].voyage):
        i = "interpolated/interpolated_" + i + f'processed_below_3knot_{interpolation_number}'
        df = pd.read_csv(upper_china_path_dir + i + ".csv")
        high_speed_path_data.append(df)

In [16]:
all_data = pd.concat(low_speed_path_data)

# Add a new index column representing the row number
all_data['index'] = range(len(all_data))
all_data["index"] = all_data.index
concaternated_df = all_data.groupby('index').mean()
concaternated_df.to_csv(f"실험/upper_china_cosco_fos_low_speed_below_3_knot_{interpolation_number}_concaternated_df.csv", encoding="utf-8 sig",header=True, index=False)

In [17]:
all_data = pd.concat(high_speed_path_data)

# Add a new index column representing the row number
all_data['index'] = range(len(all_data))
all_data["index"] = all_data.index
concaternated_df = all_data.groupby('index').mean()
concaternated_df.to_csv(f"실험/upper_china_cosco_fos_high_speed_below_3_knot_{interpolation_number}_concaternated_df.csv", encoding="utf-8 sig",header=True, index=False)

In [18]:
result_df_dict=  {
    "experiment_no" : [],
    "mean_speed" : [],
    "max_speed" : []
}

In [19]:
# 가는 길인데 굳이 오래 돌아갈 필요는 없잖아 알고리즘
def optimal_next_point(current_position, shortest_point_idx, shortest_distance,
                       path_df):
    posi_c = current_position
    latitude_i = path_df.loc[shortest_point_idx, "latitude"]
    longitude_i = path_df.loc[shortest_point_idx, "longitude"]
    posi_i = (latitude_i, longitude_i)
    min_d = shortest_distance
    n = shortest_point_idx + 1
    while True:
        try:
            latitude_n = path_df.loc[n, "latitude"]
            longitude_n = path_df.loc[n, "longitude"]
            posi_n = (latitude_n, longitude_n)
            distance = haversine(posi_c, posi_n, unit="km")
            if n == shortest_point_idx + 1:
                path_distance = haversine(posi_i, posi_n, unit="km")
                paths_distance = path_distance
            else:
                path_distance = haversine(posi_n, posi_previous_n, unit="km")
                paths_distance += path_distance

            if distance < (paths_distance + min_d):
                optimal_next_point_idx = n
                return optimal_next_point_idx
            elif n == path_df.index[-1]:
                print("no better optimal_point")
                return shortest_point_idx + 1
            else:
                n = n + 1
                posi_previous_n = posi_n
        except:
            print("no better optimal_point")
            return shortest_point_idx + 1

In [20]:
# 인덱스 번호를 가지고 항로의 segment 번호를 찾음
# 만약 segment의 마지막 번호라면 seg_no를 하나 더한다.

def find_segment_no(optimal_point_idx, path_df, the_number_of_seg):
    seg_no = optimal_point_idx // (len(path_df) / the_number_of_seg)
    next_no = (optimal_point_idx + 1) // (len(path_df) / the_number_of_seg)
    if seg_no != next_no:
        return int(next_no)
    else:
        return int(seg_no)

In [21]:
# df 내의 포인트 전체 길이 구하는 함수
def reckon_point_lengths(df_test_2):
    distance = 0
    df_test_2.reset_index(inplace=True, drop=True)
    for idx in df_test_2.index:
        if idx != 0:
            LONGITUDE = df_test_2.loc[idx, "longitude"]
            LATITUDE = df_test_2.loc[idx, "latitude"]
            current_coord = (LATITUDE, LONGITUDE)

            LONGITUDE = df_test_2.loc[idx - 1, "longitude"]
            LATITUDE = df_test_2.loc[idx - 1, "latitude"]
            previous_current_coord = (LATITUDE, LONGITUDE)

            distance += haversine(current_coord, previous_current_coord, unit="km")
    return distance

In [22]:
def cal_duration(speed, distance):
    hour = int(distance // km_h)
    minute = int(
        (distance / km_h - hour) * 60)
    second = ((distance / km_h - hour) * 60 - minute) * 60
    duration = datetime.timedelta(hours=hour,minutes=minute, seconds=second)
    return duration

In [23]:
high_speed_interpolated_df = pd.read_csv(f"실험/upper_china_cosco_fos_high_speed_below_3_knot_{interpolation_number}_concaternated_df.csv")
high_speed_interpolated_df

         timestamp   longitude   latitude      speed
0     1.668396e+09  117.884550  38.953275  11.650000
1     1.668396e+09  117.885810  38.952988  11.708276
2     1.668396e+09  117.887070  38.952701  11.766553
3     1.668396e+09  117.888330  38.952414  11.824829
4     1.668396e+09  117.889589  38.952127  11.883105
...            ...         ...        ...        ...
9995  1.668547e+09  128.848323  34.915710  10.587933
9996  1.668547e+09  128.848054  34.916489  10.584700
9997  1.668547e+09  128.847786  34.917268  10.581466
9998  1.668547e+09  128.847518  34.918046  10.578233
9999  1.668547e+09  128.847250  34.918825  10.575000

[10000 rows x 4 columns]

In [24]:
low_speed_interpolated_df = pd.read_csv(f"실험/upper_china_cosco_fos_low_speed_below_3_knot_{interpolation_number}_concaternated_df.csv")
low_speed_interpolated_df

         timestamp   longitude   latitude      speed
0     1.668974e+09  117.979120  38.933880  10.280000
1     1.668974e+09  117.981084  38.933637  10.388327
2     1.668974e+09  117.983048  38.933394  10.496653
3     1.668974e+09  117.985012  38.933151  10.604980
4     1.668974e+09  117.986977  38.932908  10.713307
...            ...         ...        ...        ...
9995  1.669262e+09  128.856269  34.909660   8.835972
9996  1.669262e+09  128.855447  34.910475   8.826979
9997  1.669262e+09  128.854625  34.911290   8.817986
9998  1.669262e+09  128.853802  34.912105   8.808993
9999  1.669262e+09  128.852980  34.912920   8.800000

[10000 rows x 4 columns]

## segment 100

In [25]:
the_number_of_seg = 100

In [26]:
seg_length = int(len(high_speed_interpolated_df) / the_number_of_seg)

In [27]:
high_speed_df_list = []
for i in range(the_number_of_seg):
    idx = seg_length * (i + 1)
    if i == 0:
        df = high_speed_interpolated_df.loc[0:idx - 1]
        df.reset_index(inplace=True)
    else:
        df = high_speed_interpolated_df.loc[idx - seg_length:idx - 1]
        df.reset_index(inplace=True)
    high_speed_df_list.append(df)

# ETA 실험 (interpolation 10000), COSCO FOS 26항차

In [28]:
cosco_fos_voy_number = "26"

In [29]:
high_speed_interpolated_df = pd.read_csv(f"실험/upper_china_cosco_fos_high_speed_below_3_knot_{interpolation_number}_concaternated_df.csv")
high_speed_interpolated_df

         timestamp   longitude   latitude      speed
0     1.668396e+09  117.884550  38.953275  11.650000
1     1.668396e+09  117.885810  38.952988  11.708276
2     1.668396e+09  117.887070  38.952701  11.766553
3     1.668396e+09  117.888330  38.952414  11.824829
4     1.668396e+09  117.889589  38.952127  11.883105
...            ...         ...        ...        ...
9995  1.668547e+09  128.848323  34.915710  10.587933
9996  1.668547e+09  128.848054  34.916489  10.584700
9997  1.668547e+09  128.847786  34.917268  10.581466
9998  1.668547e+09  128.847518  34.918046  10.578233
9999  1.668547e+09  128.847250  34.918825  10.575000

[10000 rows x 4 columns]

In [30]:
low_speed_interpolated_df = pd.read_csv(f"실험/upper_china_cosco_fos_low_speed_below_3_knot_{interpolation_number}_concaternated_df.csv")
low_speed_interpolated_df

         timestamp   longitude   latitude      speed
0     1.668974e+09  117.979120  38.933880  10.280000
1     1.668974e+09  117.981084  38.933637  10.388327
2     1.668974e+09  117.983048  38.933394  10.496653
3     1.668974e+09  117.985012  38.933151  10.604980
4     1.668974e+09  117.986977  38.932908  10.713307
...            ...         ...        ...        ...
9995  1.669262e+09  128.856269  34.909660   8.835972
9996  1.669262e+09  128.855447  34.910475   8.826979
9997  1.669262e+09  128.854625  34.911290   8.817986
9998  1.669262e+09  128.853802  34.912105   8.808993
9999  1.669262e+09  128.852980  34.912920   8.800000

[10000 rows x 4 columns]

## segment 100

In [31]:
the_number_of_seg = 100

In [32]:
seg_length = int(len(high_speed_interpolated_df) / the_number_of_seg)

In [33]:
high_speed_df_list = []
for i in range(the_number_of_seg):
    idx = seg_length * (i + 1)
    if i == 0:
        df = high_speed_interpolated_df.loc[0:idx - 1]
        df.reset_index(inplace=True)
    else:
        df = high_speed_interpolated_df.loc[idx - seg_length:idx - 1]
        df.reset_index(inplace=True)
    high_speed_df_list.append(df)

In [34]:
# for df in high_speed_df_list:
#     d = df["speed"].mean()
#     print(d)

### 고속 (7knot 미만 제거)

#### 3. 순간 속력 이용 + 알고리즘 x  +  감속 계수 x

In [35]:
test_df_26 = pd.read_csv(f"voy_path/upper_china/processed/COSCO_FOS_VRKR6_2022_{cosco_fos_voy_number}processed.csv")
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['time_voyage_data_received'] = pd.to_datetime(test_df_26['time_voyage_data_received'])
test_df_26.drop('index', axis=1, inplace=True)
test_df_26 = test_df_26.loc[test_df_26[['longitude','latitude','timestamp']].drop_duplicates().index]
test_df_26.reset_index(inplace=True, drop=True)

In [36]:
for col in test_df_26.index:
    if col == test_df_26.index[-8]:
        break
    # 테스트 데이터
    re_sample = test_df_26.loc[col,:]
    longitude = re_sample["longitude"]
    latitude = re_sample["latitude"]
    current_point = (latitude, longitude)
    
    # 1. 순간 속력 (AIS) 
    current_speed = re_sample["speed"]
    current_position_timestamp = re_sample["timestamp"]
    if current_speed < 7:
        continue
    # 현재 위치에서 가장 짧은 segment 찾기
    shortest_distance = 9999
    for seg_no, seg_df in enumerate(high_speed_df_list):
        for idx in seg_df.index:
            LONGITUDE = seg_df.loc[idx, "longitude"]
            LATITUDE = seg_df.loc[idx, "latitude"]

            ais_point = (LATITUDE, LONGITUDE)
            distance = haversine(current_point, ais_point, unit="km")
            # 가장 짧은 segment 간의 거리, segment 번호, 인덱스 저장
            if distance <= shortest_distance:
                shortest_distance = distance 
                shortest_point_idx = seg_df.loc[idx, "index"]
                shortest_seg_no = seg_no
                
    # 다음 인덱스
#     optimal_point_idx = optimal_next_point(current_point, shortest_point_idx, shortest_distance, high_speed_interpolated_df)
    optimal_point_idx = high_speed_interpolated_df.query(f'index == {shortest_point_idx}').index[0] + 1
    lon_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "longitude"]
    lat_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "latitude"]
    
    optimal_point = (lat_optimal, lon_optimal)
    optimal_distance = haversine(current_point, optimal_point, unit="km")
    km_h = current_speed * 1.852
    init_duration = cal_duration(km_h, optimal_distance)
    
    
    # 가장 가까운 segment 찾기
    
    optimal_seg_no = find_segment_no(optimal_point_idx, high_speed_interpolated_df, the_number_of_seg)
    if optimal_seg_no == the_number_of_seg:
        continue
    initial_seg_df = high_speed_df_list[optimal_seg_no]
    # speed_damping_ratio는 각 segment에 맞게
#     speed_damping_ratio = current_speed / initial_seg_df["speed"].mean()
    speed_damping_ratio = 1
    km_h = current_speed * 1.852 * speed_damping_ratio
    
    
    remaining_initial_seg_df = initial_seg_df.loc[optimal_point_idx:,:]
    remaining_initial_seg_df.reset_index(inplace=True, drop=True)
    accu_distance = 0
    for idx in remaining_initial_seg_df.index:
        if idx != 0:
            LONGITUDE = remaining_initial_seg_df.loc[idx, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx, "latitude"]
            current_coord = (LATITUDE, LONGITUDE)

            LONGITUDE = remaining_initial_seg_df.loc[idx - 1, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx - 1, "latitude"]
            previous_current_coord = (LATITUDE, LONGITUDE)
            
            accu_distance += haversine(current_coord, previous_current_coord, unit="km")
            
    duration_0 = cal_duration(km_h, accu_distance)
    duration_0 = duration_0 + init_duration
    
    
        
    dura_list = []  
    for next_seg_no in range(optimal_seg_no + 1, the_number_of_seg):
        next_seg_df = high_speed_df_list[next_seg_no]
        
        seg_mean_speed = next_seg_df['speed'].mean()
#         speed_damping_ratio = current_speed / seg_mean_speed
        speed_damping_ratio = 1
        damped_mean_speed = seg_mean_speed * speed_damping_ratio
        km_h = damped_mean_speed * 1.852
        distance = reckon_point_lengths(next_seg_df)
        dura_list.append(cal_duration(km_h, distance))
    
    accu_timedelta = datetime.timedelta(seconds=0)
    for i in dura_list:
        accu_timedelta += i
    # 현재 시간 + duration = ETA
    ETA = current_position_timestamp + accu_timedelta
    test_df_26.loc[col,'ETA'] = ETA
    optimal_seg_no = 0

test_df_26['ATA'] = test_df_26.loc[test_df_26.index[-1],"timestamp"]
test_df_26['error'] = abs(test_df_26['ATA'] - test_df_26['ETA'])

experiment_no = f"4.1.1.1_seg_{the_number_of_seg}_{cosco_fos_voy_number}".replace(".","_")
result_df_dict['experiment_no'].append(experiment_no)
result_df_dict['mean_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].mean())
result_df_dict['max_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].max())

globals()[f"exp_result_df_{experiment_no}"] = test_df_26

In [37]:
print("최대:", test_df_26.loc[test_df_26.index[:-20]]["error"].max())
print("평균:", test_df_26.loc[test_df_26.index[:-20]]["error"].mean())

최대: 0 days 01:56:13.045933
평균: 0 days 00:56:06.123337581

In [38]:
test_df_26.loc[test_df_26['error'].dropna(axis=0).index].sort_values(by="error")

,vessel_name,mmsi,imo,CAPACITY,destination,eta,longitude,latitude,speed,heading,timestamp,time_position_data_received,time_voyage_data_received,navigation_info,remained_distance,estimated_fuel_consumption,ETA,ATA,error
156,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,125.5776,34.4946,17.1,174.0,2022-11-21 02:45:40.125967,2022-11-20 17:43:09,2022-11-20 02:37:09,under way using engine,300.906501,539.627890,2022-11-21 16:25:10.754607,2022-11-21 16:50:10.106911,0 days 00:24:59.352304
279,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,128.7680,34.6024,13.7,30.0,2022-11-21 14:46:30.615843,2022-11-21 05:25:08,2022-11-21 05:13:07,under way using engine,41.100285,58.938203,2022-11-21 16:24:45.319897,2022-11-21 16:50:10.106911,0 days 00:25:24.787014
224,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,127.3412,34.1147,16.6,84.0,2022-11-21 09:34:30.574857,2022-11-21 00:30:35,2022-11-20 02:37:09,under way using engine,165.431533,286.352701,2022-11-21 16:23:18.785252,2022-11-21 16:50:10.106911,0 days 00:26:51.321659
219,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,127.2102,34.0851,15.9,71.0,2022-11-21 09:09:16.770038,2022-11-21 00:05:27.000000,2022-11-20 02:37:09,under way using engine,177.213609,292.204786,2022-11-21 16:22:37.874869,2022-11-21 16:50:10.106911,0 days 00:27:32.232042
214,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,127.0898,34.0743,16.1,85.0,2022-11-21 08:44:02.042933,2022-11-20 23:42:56.000000,2022-11-20 02:37:09,under way using engine,187.133416,312.828798,2022-11-21 16:21:49.377529,2022-11-21 16:50:10.106911,0 days 00:28:20.729382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,118.5464,38.8090,15.9,99.0,2022-11-20 00:56:08.941787,2022-11-19 15:52:02,2022-11-19 03:43:06,under way using engine,1007.627317,1661.461136,2022-11-21 15:05:19.117550,2022-11-21 16:50:10.106911,0 days 01:44:50.989361
2,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,118.1518,38.8866,15.5,120.0,2022-11-19 23:40:25.952188,2022-11-19 14:36:02,2022-11-19 02:37:12,under way using engine,1042.573266,1673.171691,2022-11-21 15:05:04.220137,2022-11-21 16:50:10.106911,0 days 01:45:05.886774
7,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,118.4220,38.8213,15.9,95.0,2022-11-20 00:30:54.499802,2022-11-19 15:29:58.000000,2022-11-19 03:19:08,under way using engine,1018.143579,1678.801238,2022-11-21 15:04:42.651653,2022-11-21 16:50:10.106911,0 days 01:45:27.455258
6,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,118.3764,38.8241,15.7,95.0,2022-11-20 00:25:51.522825,2022-11-19 15:21:39.000000,2022-11-19 03:19:08,under way using engine,1021.930852,1662.275118,2022-11-21 14:59:39.674676,2022-11-21 16:50:10.106911,0 days 01:50:30.432235
4,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,118.2230,38.8488,15.3,113.0,2022-11-19 23:55:34.554597,2022-11-19 14:51:38.000000,2022-11-19 02:55:09,under way using engine,1035.301317,1639.532376,2022-11-21 14:53:57.060978,2022-11-21 16:50:10.106911,0 days 01:56:13.045933

### 고속 (7knot 미만 포함)

#### 3. 순간 속력 이용 + 알고리즘 x  +  감속 계수 x

In [39]:
test_df_26 = pd.read_csv("voy_path/upper_china/processed/COSCO_FOS_VRKR6_2022_26processed.csv")
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['time_voyage_data_received'] = pd.to_datetime(test_df_26['time_voyage_data_received'])
test_df_26.drop('index', axis=1, inplace=True)
test_df_26 = test_df_26.loc[test_df_26[['longitude','latitude','timestamp']].drop_duplicates().index]
test_df_26.reset_index(inplace=True, drop=True)

In [40]:
for col in test_df_26.index:
    if col == test_df_26.index[-8]:
        break
    # 테스트 데이터
    re_sample = test_df_26.loc[col,:]
    longitude = re_sample["longitude"]
    latitude = re_sample["latitude"]
    current_point = (latitude, longitude)
    
    # 1. 순간 속력 (AIS) 
    current_speed = re_sample["speed"]
    current_position_timestamp = re_sample["timestamp"]
#     if current_speed < 7:
#         continue
    # 현재 위치에서 가장 짧은 segment 찾기
    shortest_distance = 9999
    for seg_no, seg_df in enumerate(high_speed_df_list):
        for idx in seg_df.index:
            LONGITUDE = seg_df.loc[idx, "longitude"]
            LATITUDE = seg_df.loc[idx, "latitude"]

            ais_point = (LATITUDE, LONGITUDE)
            distance = haversine(current_point, ais_point, unit="km")
            # 가장 짧은 segment 간의 거리, segment 번호, 인덱스 저장
            if distance <= shortest_distance:
                shortest_distance = distance 
                shortest_point_idx = seg_df.loc[idx, "index"]
                shortest_seg_no = seg_no
                
    # 다음 인덱스
#     optimal_point_idx = optimal_next_point(current_point, shortest_point_idx, shortest_distance, high_speed_interpolated_df)
    optimal_point_idx = high_speed_interpolated_df.query(f'index == {shortest_point_idx}').index[0] + 1
    lon_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "longitude"]
    lat_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "latitude"]
    
    optimal_point = (lat_optimal, lon_optimal)
    optimal_distance = haversine(current_point, optimal_point, unit="km")
    km_h = current_speed * 1.852
    init_duration = cal_duration(km_h, optimal_distance)
    
    
    # 가장 가까운 segment 찾기
    
    optimal_seg_no = find_segment_no(optimal_point_idx, high_speed_interpolated_df, the_number_of_seg)
    if optimal_seg_no == the_number_of_seg:
        continue
    initial_seg_df = high_speed_df_list[optimal_seg_no]
    # speed_damping_ratio는 각 segment에 맞게
#     speed_damping_ratio = current_speed / initial_seg_df["speed"].mean()
    speed_damping_ratio = 1
    km_h = current_speed * 1.852 * speed_damping_ratio
    
    
    remaining_initial_seg_df = initial_seg_df.loc[optimal_point_idx:,:]
    remaining_initial_seg_df.reset_index(inplace=True, drop=True)
    accu_distance = 0
    for idx in remaining_initial_seg_df.index:
        if idx != 0:
            LONGITUDE = remaining_initial_seg_df.loc[idx, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx, "latitude"]
            current_coord = (LATITUDE, LONGITUDE)

            LONGITUDE = remaining_initial_seg_df.loc[idx - 1, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx - 1, "latitude"]
            previous_current_coord = (LATITUDE, LONGITUDE)
            
            accu_distance += haversine(current_coord, previous_current_coord, unit="km")
            
    duration_0 = cal_duration(km_h, accu_distance)
    duration_0 = duration_0 + init_duration
    
    
        
    dura_list = []  
    for next_seg_no in range(optimal_seg_no + 1, the_number_of_seg):
        next_seg_df = high_speed_df_list[next_seg_no]
        
        seg_mean_speed = next_seg_df['speed'].mean()
#         speed_damping_ratio = current_speed / seg_mean_speed
        speed_damping_ratio = 1
        damped_mean_speed = seg_mean_speed * speed_damping_ratio
        km_h = damped_mean_speed * 1.852
        distance = reckon_point_lengths(next_seg_df)
        dura_list.append(cal_duration(km_h, distance))
    
    accu_timedelta = datetime.timedelta(seconds=0)
    for i in dura_list:
        accu_timedelta += i
    # 현재 시간 + duration = ETA
    ETA = current_position_timestamp + accu_timedelta
    test_df_26.loc[col,'ETA'] = ETA
    optimal_seg_no = 0

test_df_26['ATA'] = test_df_26.loc[test_df_26.index[-1],"timestamp"]
test_df_26['error'] = abs(test_df_26['ATA'] - test_df_26['ETA'])

experiment_no = f"4.1.2.1_seg_{the_number_of_seg}_{cosco_fos_voy_number}".replace(".","_")
result_df_dict['experiment_no'].append(experiment_no)
result_df_dict['mean_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].mean())
result_df_dict['max_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].max())

globals()[f"exp_result_df_{experiment_no}"] = test_df_26

In [41]:
print("최대:", test_df_26.loc[test_df_26.index[:-20]]["error"].max())
print("평균:", test_df_26.loc[test_df_26.index[:-20]]["error"].mean())

최대: 0 days 01:56:13.045933
평균: 0 days 00:56:06.123337581

In [42]:
test_df_26.loc[test_df_26['error'].dropna(axis=0).index].sort_values(by="error")

,vessel_name,mmsi,imo,CAPACITY,destination,eta,longitude,latitude,speed,heading,timestamp,time_position_data_received,time_voyage_data_received,navigation_info,remained_distance,estimated_fuel_consumption,ETA,ATA,error
156,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,125.5776,34.4946,17.1,174.0,2022-11-21 02:45:40.125967,2022-11-20 17:43:09,2022-11-20 02:37:09,under way using engine,300.906501,539.627890,2022-11-21 16:25:10.754607,2022-11-21 16:50:10.106911,0 days 00:24:59.352304
279,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,128.7680,34.6024,13.7,30.0,2022-11-21 14:46:30.615843,2022-11-21 05:25:08,2022-11-21 05:13:07,under way using engine,41.100285,58.938203,2022-11-21 16:24:45.319897,2022-11-21 16:50:10.106911,0 days 00:25:24.787014
224,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,127.3412,34.1147,16.6,84.0,2022-11-21 09:34:30.574857,2022-11-21 00:30:35,2022-11-20 02:37:09,under way using engine,165.431533,286.352701,2022-11-21 16:23:18.785252,2022-11-21 16:50:10.106911,0 days 00:26:51.321659
219,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,127.2102,34.0851,15.9,71.0,2022-11-21 09:09:16.770038,2022-11-21 00:05:27.000000,2022-11-20 02:37:09,under way using engine,177.213609,292.204786,2022-11-21 16:22:37.874869,2022-11-21 16:50:10.106911,0 days 00:27:32.232042
214,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,127.0898,34.0743,16.1,85.0,2022-11-21 08:44:02.042933,2022-11-20 23:42:56.000000,2022-11-20 02:37:09,under way using engine,187.133416,312.828798,2022-11-21 16:21:49.377529,2022-11-21 16:50:10.106911,0 days 00:28:20.729382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,118.5464,38.8090,15.9,99.0,2022-11-20 00:56:08.941787,2022-11-19 15:52:02,2022-11-19 03:43:06,under way using engine,1007.627317,1661.461136,2022-11-21 15:05:19.117550,2022-11-21 16:50:10.106911,0 days 01:44:50.989361
2,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,118.1518,38.8866,15.5,120.0,2022-11-19 23:40:25.952188,2022-11-19 14:36:02,2022-11-19 02:37:12,under way using engine,1042.573266,1673.171691,2022-11-21 15:05:04.220137,2022-11-21 16:50:10.106911,0 days 01:45:05.886774
7,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,118.4220,38.8213,15.9,95.0,2022-11-20 00:30:54.499802,2022-11-19 15:29:58.000000,2022-11-19 03:19:08,under way using engine,1018.143579,1678.801238,2022-11-21 15:04:42.651653,2022-11-21 16:50:10.106911,0 days 01:45:27.455258
6,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,118.3764,38.8241,15.7,95.0,2022-11-20 00:25:51.522825,2022-11-19 15:21:39.000000,2022-11-19 03:19:08,under way using engine,1021.930852,1662.275118,2022-11-21 14:59:39.674676,2022-11-21 16:50:10.106911,0 days 01:50:30.432235
4,COSCO FOS,477947700,9484302.0,4253,KRBNP,11210800,118.2230,38.8488,15.3,113.0,2022-11-19 23:55:34.554597,2022-11-19 14:51:38.000000,2022-11-19 02:55:09,under way using engine,1035.301317,1639.532376,2022-11-21 14:53:57.060978,2022-11-21 16:50:10.106911,0 days 01:56:13.045933

# ETA 실험 (interpolation 10000), COSCO FOS 23항차

In [43]:
cosco_fos_voy_number = "23"

In [44]:
high_speed_interpolated_df = pd.read_csv(f"실험/upper_china_cosco_fos_high_speed_below_3_knot_{interpolation_number}_concaternated_df.csv")
high_speed_interpolated_df

         timestamp   longitude   latitude      speed
0     1.668396e+09  117.884550  38.953275  11.650000
1     1.668396e+09  117.885810  38.952988  11.708276
2     1.668396e+09  117.887070  38.952701  11.766553
3     1.668396e+09  117.888330  38.952414  11.824829
4     1.668396e+09  117.889589  38.952127  11.883105
...            ...         ...        ...        ...
9995  1.668547e+09  128.848323  34.915710  10.587933
9996  1.668547e+09  128.848054  34.916489  10.584700
9997  1.668547e+09  128.847786  34.917268  10.581466
9998  1.668547e+09  128.847518  34.918046  10.578233
9999  1.668547e+09  128.847250  34.918825  10.575000

[10000 rows x 4 columns]

In [45]:
low_speed_interpolated_df = pd.read_csv(f"실험/upper_china_cosco_fos_low_speed_below_3_knot_{interpolation_number}_concaternated_df.csv")
low_speed_interpolated_df

         timestamp   longitude   latitude      speed
0     1.668974e+09  117.979120  38.933880  10.280000
1     1.668974e+09  117.981084  38.933637  10.388327
2     1.668974e+09  117.983048  38.933394  10.496653
3     1.668974e+09  117.985012  38.933151  10.604980
4     1.668974e+09  117.986977  38.932908  10.713307
...            ...         ...        ...        ...
9995  1.669262e+09  128.856269  34.909660   8.835972
9996  1.669262e+09  128.855447  34.910475   8.826979
9997  1.669262e+09  128.854625  34.911290   8.817986
9998  1.669262e+09  128.853802  34.912105   8.808993
9999  1.669262e+09  128.852980  34.912920   8.800000

[10000 rows x 4 columns]

## segment 100

In [46]:
the_number_of_seg = 100

In [47]:
seg_length = int(len(high_speed_interpolated_df) / the_number_of_seg)

In [48]:
high_speed_df_list = []
for i in range(the_number_of_seg):
    idx = seg_length * (i + 1)
    if i == 0:
        df = high_speed_interpolated_df.loc[0:idx - 1]
        df.reset_index(inplace=True)
    else:
        df = high_speed_interpolated_df.loc[idx - seg_length:idx - 1]
        df.reset_index(inplace=True)
    high_speed_df_list.append(df)

In [49]:
# for df in high_speed_df_list:
#     d = df["speed"].mean()
#     print(d)

### 고속 (7knot 미만 제거)

#### 3. 순간 속력 이용 + 알고리즘 x  +  감속 계수 x

In [50]:
test_df_26 = pd.read_csv(f"voy_path/upper_china/processed/COSCO_FOS_VRKR6_2022_{cosco_fos_voy_number}processed.csv")
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['time_voyage_data_received'] = pd.to_datetime(test_df_26['time_voyage_data_received'])
test_df_26.drop('index', axis=1, inplace=True)
test_df_26 = test_df_26.loc[test_df_26[['longitude','latitude','timestamp']].drop_duplicates().index]
test_df_26.reset_index(inplace=True, drop=True)

In [51]:
for col in test_df_26.index:
    if col == test_df_26.index[-8]:
        break
    # 테스트 데이터
    re_sample = test_df_26.loc[col,:]
    longitude = re_sample["longitude"]
    latitude = re_sample["latitude"]
    current_point = (latitude, longitude)
    
    # 1. 순간 속력 (AIS) 
    current_speed = re_sample["speed"]
    current_position_timestamp = re_sample["timestamp"]
    if current_speed < 7:
        continue
    # 현재 위치에서 가장 짧은 segment 찾기
    shortest_distance = 9999
    for seg_no, seg_df in enumerate(high_speed_df_list):
        for idx in seg_df.index:
            LONGITUDE = seg_df.loc[idx, "longitude"]
            LATITUDE = seg_df.loc[idx, "latitude"]

            ais_point = (LATITUDE, LONGITUDE)
            distance = haversine(current_point, ais_point, unit="km")
            # 가장 짧은 segment 간의 거리, segment 번호, 인덱스 저장
            if distance <= shortest_distance:
                shortest_distance = distance 
                shortest_point_idx = seg_df.loc[idx, "index"]
                shortest_seg_no = seg_no
                
    # 다음 인덱스
#     optimal_point_idx = optimal_next_point(current_point, shortest_point_idx, shortest_distance, high_speed_interpolated_df)
    optimal_point_idx = high_speed_interpolated_df.query(f'index == {shortest_point_idx}').index[0] + 1
    lon_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "longitude"]
    lat_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "latitude"]
    
    optimal_point = (lat_optimal, lon_optimal)
    optimal_distance = haversine(current_point, optimal_point, unit="km")
    km_h = current_speed * 1.852
    init_duration = cal_duration(km_h, optimal_distance)
    
    
    # 가장 가까운 segment 찾기
    
    optimal_seg_no = find_segment_no(optimal_point_idx, high_speed_interpolated_df, the_number_of_seg)
    if optimal_seg_no == the_number_of_seg:
        continue
    initial_seg_df = high_speed_df_list[optimal_seg_no]
    # speed_damping_ratio는 각 segment에 맞게
#     speed_damping_ratio = current_speed / initial_seg_df["speed"].mean()
    speed_damping_ratio = 1
    km_h = current_speed * 1.852 * speed_damping_ratio
    
    
    remaining_initial_seg_df = initial_seg_df.loc[optimal_point_idx:,:]
    remaining_initial_seg_df.reset_index(inplace=True, drop=True)
    accu_distance = 0
    for idx in remaining_initial_seg_df.index:
        if idx != 0:
            LONGITUDE = remaining_initial_seg_df.loc[idx, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx, "latitude"]
            current_coord = (LATITUDE, LONGITUDE)

            LONGITUDE = remaining_initial_seg_df.loc[idx - 1, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx - 1, "latitude"]
            previous_current_coord = (LATITUDE, LONGITUDE)
            
            accu_distance += haversine(current_coord, previous_current_coord, unit="km")
            
    duration_0 = cal_duration(km_h, accu_distance)
    duration_0 = duration_0 + init_duration
    
    
        
    dura_list = []  
    for next_seg_no in range(optimal_seg_no + 1, the_number_of_seg):
        next_seg_df = high_speed_df_list[next_seg_no]
        
        seg_mean_speed = next_seg_df['speed'].mean()
#         speed_damping_ratio = current_speed / seg_mean_speed
        speed_damping_ratio = 1
        damped_mean_speed = seg_mean_speed * speed_damping_ratio
        km_h = damped_mean_speed * 1.852
        distance = reckon_point_lengths(next_seg_df)
        dura_list.append(cal_duration(km_h, distance))
    
    accu_timedelta = datetime.timedelta(seconds=0)
    for i in dura_list:
        accu_timedelta += i
    # 현재 시간 + duration = ETA
    ETA = current_position_timestamp + accu_timedelta
    test_df_26.loc[col,'ETA'] = ETA
    optimal_seg_no = 0

test_df_26['ATA'] = test_df_26.loc[test_df_26.index[-1],"timestamp"]
test_df_26['error'] = abs(test_df_26['ATA'] - test_df_26['ETA'])

experiment_no = f"5.1.1.1_seg_{the_number_of_seg}_{cosco_fos_voy_number}".replace(".","_")
result_df_dict['experiment_no'].append(experiment_no)
result_df_dict['mean_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].mean())
result_df_dict['max_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].max())

globals()[f"exp_result_df_{experiment_no}"] = test_df_26

In [52]:
print("최대:", test_df_26.loc[test_df_26.index[:-20]]["error"].max())
print("평균:", test_df_26.loc[test_df_26.index[:-20]]["error"].mean())

최대: 0 days 00:34:46.370161
평균: 0 days 00:13:18.045748263

In [53]:
test_df_26.loc[test_df_26['error'].dropna(axis=0).index].sort_values(by="error")

,vessel_name,mmsi,imo,CAPACITY,destination,eta,longitude,latitude,speed,heading,timestamp,time_position_data_received,time_voyage_data_received,navigation_info,remained_distance,estimated_fuel_consumption,ETA,ATA,error
62,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,125.0814,35.4694,18.3,149.0,2022-10-27 17:33:19.239844,2022-10-27 08:31:48.000000,2022-10-26 10:37:08,under way using engine,344.062371,672.807987,2022-10-28 10:23:51.654186,2022-10-28 10:23:54.026414,0 days 00:00:02.372228
28,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,121.2544,38.4186,17.8,114.0,2022-10-27 03:15:16.183586,2022-10-26 18:10:11.000000,2022-10-26 06:01:09,under way using engine,775.520696,1462.503387,2022-10-28 10:24:08.184327,2022-10-28 10:23:54.026414,0 days 00:00:14.157913
4,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,118.0623,38.9239,7.9,115.0,2022-10-26 18:35:24.201537,2022-10-26 09:32:47.000000,2022-10-26 09:31:09,under way using engine,1051.296999,1359.529438,2022-10-28 10:23:29.475267,2022-10-28 10:23:54.026414,0 days 00:00:24.551147
81,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,125.5291,34.9206,20.1,138.0,2022-10-27 19:35:37.026986,2022-10-27 10:35:18,2022-10-26 10:37:08,under way using engine,299.940646,668.881610,2022-10-28 10:24:26.658289,2022-10-28 10:23:54.026414,0 days 00:00:32.631875
67,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,125.1754,35.3553,18.8,146.0,2022-10-27 17:58:33.189439,2022-10-27 08:58:23.000000,2022-10-26 10:37:08,under way using engine,334.005348,677.379946,2022-10-28 10:24:28.817064,2022-10-28 10:23:54.026414,0 days 00:00:34.790650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,126.1072,34.0469,14.5,91.0,2022-10-27 23:22:44.890969,2022-10-27 14:18:47.000000,2022-10-26 10:37:08,under way using engine,268.855517,404.421851,2022-10-28 09:52:26.486265,2022-10-28 10:23:54.026414,0 days 00:31:27.540149
111,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,125.8217,34.0685,18.5,97.0,2022-10-27 22:32:16.302110,2022-10-27 13:29:13.000000,2022-10-26 10:37:08,under way using engine,292.337987,580.046101,2022-10-28 09:51:01.899029,2022-10-28 10:23:54.026414,0 days 00:32:52.127385
106,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,125.6902,34.1040,18.9,123.0,2022-10-27 22:07:02.412834,2022-10-27 13:06:24.000000,2022-10-26 10:37:08,under way using engine,302.345587,617.665056,2022-10-28 09:50:44.011754,2022-10-28 10:23:54.026414,0 days 00:33:10.014660
125,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,126.3288,34.0530,13.7,92.0,2022-10-28 00:08:10.402016,2022-10-27 15:06:24.000000,2022-10-26 10:37:08,under way using engine,249.924158,358.393636,2022-10-28 09:49:17.020788,2022-10-28 10:23:54.026414,0 days 00:34:37.005626
120,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,126.2138,34.0512,13.8,87.0,2022-10-27 23:42:56.047960,2022-10-27 14:41:24.000000,2022-10-26 10:37:08,under way using engine,259.660726,374.499938,2022-10-28 09:49:07.656253,2022-10-28 10:23:54.026414,0 days 00:34:46.370161

### 고속 (7knot 미만 포함)

#### 3. 순간 속력 이용 + 알고리즘 x  +  감속 계수 x

In [54]:
test_df_26 = pd.read_csv(f"voy_path/upper_china/processed/COSCO_FOS_VRKR6_2022_{cosco_fos_voy_number}processed.csv")
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['time_voyage_data_received'] = pd.to_datetime(test_df_26['time_voyage_data_received'])
test_df_26.drop('index', axis=1, inplace=True)
test_df_26 = test_df_26.loc[test_df_26[['longitude','latitude','timestamp']].drop_duplicates().index]
test_df_26.reset_index(inplace=True, drop=True)

In [55]:
for col in test_df_26.index:
    if col == test_df_26.index[-8]:
        break
    # 테스트 데이터
    re_sample = test_df_26.loc[col,:]
    longitude = re_sample["longitude"]
    latitude = re_sample["latitude"]
    current_point = (latitude, longitude)
    
    # 1. 순간 속력 (AIS) 
    current_speed = re_sample["speed"]
    current_position_timestamp = re_sample["timestamp"]
#     if current_speed < 7:
#         continue
    # 현재 위치에서 가장 짧은 segment 찾기
    shortest_distance = 9999
    for seg_no, seg_df in enumerate(high_speed_df_list):
        for idx in seg_df.index:
            LONGITUDE = seg_df.loc[idx, "longitude"]
            LATITUDE = seg_df.loc[idx, "latitude"]

            ais_point = (LATITUDE, LONGITUDE)
            distance = haversine(current_point, ais_point, unit="km")
            # 가장 짧은 segment 간의 거리, segment 번호, 인덱스 저장
            if distance <= shortest_distance:
                shortest_distance = distance 
                shortest_point_idx = seg_df.loc[idx, "index"]
                shortest_seg_no = seg_no
                
    # 다음 인덱스
#     optimal_point_idx = optimal_next_point(current_point, shortest_point_idx, shortest_distance, high_speed_interpolated_df)
    optimal_point_idx = high_speed_interpolated_df.query(f'index == {shortest_point_idx}').index[0] + 1
    lon_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "longitude"]
    lat_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "latitude"]
    
    optimal_point = (lat_optimal, lon_optimal)
    optimal_distance = haversine(current_point, optimal_point, unit="km")
    km_h = current_speed * 1.852
    init_duration = cal_duration(km_h, optimal_distance)
    
    
    # 가장 가까운 segment 찾기
    
    optimal_seg_no = find_segment_no(optimal_point_idx, high_speed_interpolated_df, the_number_of_seg)
    if optimal_seg_no == the_number_of_seg:
        continue
    initial_seg_df = high_speed_df_list[optimal_seg_no]
    # speed_damping_ratio는 각 segment에 맞게
#     speed_damping_ratio = current_speed / initial_seg_df["speed"].mean()
    speed_damping_ratio = 1
    km_h = current_speed * 1.852 * speed_damping_ratio
    
    
    remaining_initial_seg_df = initial_seg_df.loc[optimal_point_idx:,:]
    remaining_initial_seg_df.reset_index(inplace=True, drop=True)
    accu_distance = 0
    for idx in remaining_initial_seg_df.index:
        if idx != 0:
            LONGITUDE = remaining_initial_seg_df.loc[idx, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx, "latitude"]
            current_coord = (LATITUDE, LONGITUDE)

            LONGITUDE = remaining_initial_seg_df.loc[idx - 1, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx - 1, "latitude"]
            previous_current_coord = (LATITUDE, LONGITUDE)
            
            accu_distance += haversine(current_coord, previous_current_coord, unit="km")
            
    duration_0 = cal_duration(km_h, accu_distance)
    duration_0 = duration_0 + init_duration
    
    
        
    dura_list = []  
    for next_seg_no in range(optimal_seg_no + 1, the_number_of_seg):
        next_seg_df = high_speed_df_list[next_seg_no]
        
        seg_mean_speed = next_seg_df['speed'].mean()
#         speed_damping_ratio = current_speed / seg_mean_speed
        speed_damping_ratio = 1
        damped_mean_speed = seg_mean_speed * speed_damping_ratio
        km_h = damped_mean_speed * 1.852
        distance = reckon_point_lengths(next_seg_df)
        dura_list.append(cal_duration(km_h, distance))
    
    accu_timedelta = datetime.timedelta(seconds=0)
    for i in dura_list:
        accu_timedelta += i
    # 현재 시간 + duration = ETA
    ETA = current_position_timestamp + accu_timedelta
    test_df_26.loc[col,'ETA'] = ETA
    optimal_seg_no = 0

test_df_26['ATA'] = test_df_26.loc[test_df_26.index[-1],"timestamp"]
test_df_26['error'] = abs(test_df_26['ATA'] - test_df_26['ETA'])

experiment_no = f"5.1.2.1_seg_{the_number_of_seg}_{cosco_fos_voy_number}".replace(".","_")
result_df_dict['experiment_no'].append(experiment_no)
result_df_dict['mean_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].mean())
result_df_dict['max_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].max())

globals()[f"exp_result_df_{experiment_no}"] = test_df_26

In [56]:
print("최대:", test_df_26.loc[test_df_26.index[:-20]]["error"].max())
print("평균:", test_df_26.loc[test_df_26.index[:-20]]["error"].mean())

최대: 0 days 00:34:46.370161
평균: 0 days 00:13:18.045748263

In [57]:
test_df_26.loc[test_df_26['error'].dropna(axis=0).index].sort_values(by="error")

,vessel_name,mmsi,imo,CAPACITY,destination,eta,longitude,latitude,speed,heading,timestamp,time_position_data_received,time_voyage_data_received,navigation_info,remained_distance,estimated_fuel_consumption,ETA,ATA,error
62,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,125.0814,35.4694,18.3,149.0,2022-10-27 17:33:19.239844,2022-10-27 08:31:48.000000,2022-10-26 10:37:08,under way using engine,344.062371,672.807987,2022-10-28 10:23:51.654186,2022-10-28 10:23:54.026414,0 days 00:00:02.372228
28,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,121.2544,38.4186,17.8,114.0,2022-10-27 03:15:16.183586,2022-10-26 18:10:11.000000,2022-10-26 06:01:09,under way using engine,775.520696,1462.503387,2022-10-28 10:24:08.184327,2022-10-28 10:23:54.026414,0 days 00:00:14.157913
4,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,118.0623,38.9239,7.9,115.0,2022-10-26 18:35:24.201537,2022-10-26 09:32:47.000000,2022-10-26 09:31:09,under way using engine,1051.296999,1359.529438,2022-10-28 10:23:29.475267,2022-10-28 10:23:54.026414,0 days 00:00:24.551147
81,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,125.5291,34.9206,20.1,138.0,2022-10-27 19:35:37.026986,2022-10-27 10:35:18,2022-10-26 10:37:08,under way using engine,299.940646,668.881610,2022-10-28 10:24:26.658289,2022-10-28 10:23:54.026414,0 days 00:00:32.631875
67,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,125.1754,35.3553,18.8,146.0,2022-10-27 17:58:33.189439,2022-10-27 08:58:23.000000,2022-10-26 10:37:08,under way using engine,334.005348,677.379946,2022-10-28 10:24:28.817064,2022-10-28 10:23:54.026414,0 days 00:00:34.790650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,126.1072,34.0469,14.5,91.0,2022-10-27 23:22:44.890969,2022-10-27 14:18:47.000000,2022-10-26 10:37:08,under way using engine,268.855517,404.421851,2022-10-28 09:52:26.486265,2022-10-28 10:23:54.026414,0 days 00:31:27.540149
111,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,125.8217,34.0685,18.5,97.0,2022-10-27 22:32:16.302110,2022-10-27 13:29:13.000000,2022-10-26 10:37:08,under way using engine,292.337987,580.046101,2022-10-28 09:51:01.899029,2022-10-28 10:23:54.026414,0 days 00:32:52.127385
106,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,125.6902,34.1040,18.9,123.0,2022-10-27 22:07:02.412834,2022-10-27 13:06:24.000000,2022-10-26 10:37:08,under way using engine,302.345587,617.665056,2022-10-28 09:50:44.011754,2022-10-28 10:23:54.026414,0 days 00:33:10.014660
125,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,126.3288,34.0530,13.7,92.0,2022-10-28 00:08:10.402016,2022-10-27 15:06:24.000000,2022-10-26 10:37:08,under way using engine,249.924158,358.393636,2022-10-28 09:49:17.020788,2022-10-28 10:23:54.026414,0 days 00:34:37.005626
120,COSCO FOS,477947700,9484302.0,4253,KRBNP,10280300,126.2138,34.0512,13.8,87.0,2022-10-27 23:42:56.047960,2022-10-27 14:41:24.000000,2022-10-26 10:37:08,under way using engine,259.660726,374.499938,2022-10-28 09:49:07.656253,2022-10-28 10:23:54.026414,0 days 00:34:46.370161

# ETA 실험 (interpolation 10000), COSCO FOS 25항차

In [58]:
cosco_fos_voy_number = "25"

In [59]:
high_speed_interpolated_df = pd.read_csv(f"실험/upper_china_cosco_fos_high_speed_below_3_knot_{interpolation_number}_concaternated_df.csv")
high_speed_interpolated_df

         timestamp   longitude   latitude      speed
0     1.668396e+09  117.884550  38.953275  11.650000
1     1.668396e+09  117.885810  38.952988  11.708276
2     1.668396e+09  117.887070  38.952701  11.766553
3     1.668396e+09  117.888330  38.952414  11.824829
4     1.668396e+09  117.889589  38.952127  11.883105
...            ...         ...        ...        ...
9995  1.668547e+09  128.848323  34.915710  10.587933
9996  1.668547e+09  128.848054  34.916489  10.584700
9997  1.668547e+09  128.847786  34.917268  10.581466
9998  1.668547e+09  128.847518  34.918046  10.578233
9999  1.668547e+09  128.847250  34.918825  10.575000

[10000 rows x 4 columns]

In [60]:
low_speed_interpolated_df = pd.read_csv(f"실험/upper_china_cosco_fos_low_speed_below_3_knot_{interpolation_number}_concaternated_df.csv")
low_speed_interpolated_df

         timestamp   longitude   latitude      speed
0     1.668974e+09  117.979120  38.933880  10.280000
1     1.668974e+09  117.981084  38.933637  10.388327
2     1.668974e+09  117.983048  38.933394  10.496653
3     1.668974e+09  117.985012  38.933151  10.604980
4     1.668974e+09  117.986977  38.932908  10.713307
...            ...         ...        ...        ...
9995  1.669262e+09  128.856269  34.909660   8.835972
9996  1.669262e+09  128.855447  34.910475   8.826979
9997  1.669262e+09  128.854625  34.911290   8.817986
9998  1.669262e+09  128.853802  34.912105   8.808993
9999  1.669262e+09  128.852980  34.912920   8.800000

[10000 rows x 4 columns]

## segment 100

In [61]:
the_number_of_seg = 100

In [62]:
seg_length = int(len(high_speed_interpolated_df) / the_number_of_seg)

In [63]:
high_speed_df_list = []
for i in range(the_number_of_seg):
    idx = seg_length * (i + 1)
    if i == 0:
        df = high_speed_interpolated_df.loc[0:idx - 1]
        df.reset_index(inplace=True)
    else:
        df = high_speed_interpolated_df.loc[idx - seg_length:idx - 1]
        df.reset_index(inplace=True)
    high_speed_df_list.append(df)

In [64]:
# for df in high_speed_df_list:
#     d = df["speed"].mean()
#     print(d)

### 고속 (7knot 미만 제거)

#### 3. 순간 속력 이용 + 알고리즘 x  +  감속 계수 x

In [65]:
test_df_26 = pd.read_csv(f"voy_path/upper_china/processed/COSCO_FOS_VRKR6_2022_{cosco_fos_voy_number}processed.csv")
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['time_voyage_data_received'] = pd.to_datetime(test_df_26['time_voyage_data_received'])
test_df_26.drop('index', axis=1, inplace=True)
test_df_26 = test_df_26.loc[test_df_26[['longitude','latitude','timestamp']].drop_duplicates().index]
test_df_26.reset_index(inplace=True, drop=True)

In [66]:
for col in test_df_26.index:
    if col == test_df_26.index[-8]:
        break
    # 테스트 데이터
    re_sample = test_df_26.loc[col,:]
    longitude = re_sample["longitude"]
    latitude = re_sample["latitude"]
    current_point = (latitude, longitude)
    
    # 1. 순간 속력 (AIS) 
    current_speed = re_sample["speed"]
    current_position_timestamp = re_sample["timestamp"]
    if current_speed < 7:
        continue
    # 현재 위치에서 가장 짧은 segment 찾기
    shortest_distance = 9999
    for seg_no, seg_df in enumerate(high_speed_df_list):
        for idx in seg_df.index:
            LONGITUDE = seg_df.loc[idx, "longitude"]
            LATITUDE = seg_df.loc[idx, "latitude"]

            ais_point = (LATITUDE, LONGITUDE)
            distance = haversine(current_point, ais_point, unit="km")
            # 가장 짧은 segment 간의 거리, segment 번호, 인덱스 저장
            if distance <= shortest_distance:
                shortest_distance = distance 
                shortest_point_idx = seg_df.loc[idx, "index"]
                shortest_seg_no = seg_no
                
    # 다음 인덱스
#     optimal_point_idx = optimal_next_point(current_point, shortest_point_idx, shortest_distance, high_speed_interpolated_df)
    optimal_point_idx = high_speed_interpolated_df.query(f'index == {shortest_point_idx}').index[0] + 1
    lon_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "longitude"]
    lat_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "latitude"]
    
    optimal_point = (lat_optimal, lon_optimal)
    optimal_distance = haversine(current_point, optimal_point, unit="km")
    km_h = current_speed * 1.852
    init_duration = cal_duration(km_h, optimal_distance)
    
    
    # 가장 가까운 segment 찾기
    
    optimal_seg_no = find_segment_no(optimal_point_idx, high_speed_interpolated_df, the_number_of_seg)
    if optimal_seg_no == the_number_of_seg:
        continue
    initial_seg_df = high_speed_df_list[optimal_seg_no]
    # speed_damping_ratio는 각 segment에 맞게
#     speed_damping_ratio = current_speed / initial_seg_df["speed"].mean()
    speed_damping_ratio = 1
    km_h = current_speed * 1.852 * speed_damping_ratio
    
    
    remaining_initial_seg_df = initial_seg_df.loc[optimal_point_idx:,:]
    remaining_initial_seg_df.reset_index(inplace=True, drop=True)
    accu_distance = 0
    for idx in remaining_initial_seg_df.index:
        if idx != 0:
            LONGITUDE = remaining_initial_seg_df.loc[idx, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx, "latitude"]
            current_coord = (LATITUDE, LONGITUDE)

            LONGITUDE = remaining_initial_seg_df.loc[idx - 1, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx - 1, "latitude"]
            previous_current_coord = (LATITUDE, LONGITUDE)
            
            accu_distance += haversine(current_coord, previous_current_coord, unit="km")
            
    duration_0 = cal_duration(km_h, accu_distance)
    duration_0 = duration_0 + init_duration
    
    
        
    dura_list = []  
    for next_seg_no in range(optimal_seg_no + 1, the_number_of_seg):
        next_seg_df = high_speed_df_list[next_seg_no]
        
        seg_mean_speed = next_seg_df['speed'].mean()
#         speed_damping_ratio = current_speed / seg_mean_speed
        speed_damping_ratio = 1
        damped_mean_speed = seg_mean_speed * speed_damping_ratio
        km_h = damped_mean_speed * 1.852
        distance = reckon_point_lengths(next_seg_df)
        dura_list.append(cal_duration(km_h, distance))
    
    accu_timedelta = datetime.timedelta(seconds=0)
    for i in dura_list:
        accu_timedelta += i
    # 현재 시간 + duration = ETA
    ETA = current_position_timestamp + accu_timedelta
    test_df_26.loc[col,'ETA'] = ETA
    optimal_seg_no = 0

test_df_26['ATA'] = test_df_26.loc[test_df_26.index[-1],"timestamp"]
test_df_26['error'] = abs(test_df_26['ATA'] - test_df_26['ETA'])

experiment_no = f"6.1.1.1_seg_{the_number_of_seg}_{cosco_fos_voy_number}".replace(".","_")
result_df_dict['experiment_no'].append(experiment_no)
result_df_dict['mean_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].mean())
result_df_dict['max_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].max())

globals()[f"exp_result_df_{experiment_no}"] = test_df_26

In [67]:
print("최대:", test_df_26.loc[test_df_26.index[:-20]]["error"].max())
print("평균:", test_df_26.loc[test_df_26.index[:-20]]["error"].mean())

최대: 0 days 01:55:59.885924
평균: 0 days 00:51:07.793488160

In [68]:
test_df_26.loc[test_df_26['error'].dropna(axis=0).index].sort_values(by="error")

,vessel_name,mmsi,imo,CAPACITY,destination,eta,longitude,latitude,speed,heading,timestamp,time_position_data_received,time_voyage_data_received,navigation_info,remained_distance,estimated_fuel_consumption,ETA,ATA,error
127,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,127.2235,34.0976,18.9,80.0,2022-11-14 07:40:59.862407,2022-11-13 22:39:54,2022-11-13 06:03:53,under way using engine,175.420325,358.368072,2022-11-14 14:29:48.072802,2022-11-14 14:29:52.786142,0 days 00:00:04.713340
132,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,127.3830,34.1216,18.6,70.0,2022-11-14 08:06:14.097014,2022-11-13 23:05:42.000000,2022-11-13 06:03:53,under way using engine,161.860679,323.507171,2022-11-14 14:29:35.711722,2022-11-14 14:29:52.786142,0 days 00:00:17.074420
137,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,127.5289,34.1659,18.1,70.0,2022-11-14 08:31:28.108683,2022-11-13 23:30:54.000000,2022-11-13 06:03:53,under way using engine,148.153748,285.532243,2022-11-14 14:30:25.003449,2022-11-14 14:29:52.786142,0 days 00:00:32.217307
150,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,127.9455,34.2302,17.8,80.0,2022-11-14 09:42:08.648331,2022-11-14 00:41:37.000000,2022-11-13 06:03:53,under way using engine,114.708953,216.322056,2022-11-14 14:29:01.234260,2022-11-14 14:29:52.786142,0 days 00:00:51.551882
145,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,127.7941,34.2066,17.9,80.0,2022-11-14 09:16:54.528209,2022-11-14 00:15:54,2022-11-13 06:03:53,under way using engine,126.522328,240.332654,2022-11-14 14:28:41.340511,2022-11-14 14:29:52.786142,0 days 00:01:11.445631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,123.0270,37.6025,20.1,142.0,2022-11-13 14:16:13.292393,2022-11-13 05:12:23,2022-11-13 05:01:59,under way using engine,595.868965,1328.815541,2022-11-14 16:11:59.255820,2022-11-14 14:29:52.786142,0 days 01:42:06.469678
48,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,122.5688,37.9012,18.9,123.0,2022-11-13 12:45:22.153779,2022-11-13 03:40:41,2022-11-13 12:13:07,under way using engine,647.035778,1321.836361,2022-11-14 16:13:06.256388,2022-11-14 14:29:52.786142,0 days 01:43:13.470246
54,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,122.9137,37.7170,19.4,140.0,2022-11-13 13:56:01.931503,2022-11-13 04:50:41,2022-11-13 04:19:45,under way using engine,610.647557,1293.911531,2022-11-14 16:13:29.552211,2022-11-14 14:29:52.786142,0 days 01:43:36.766069
51,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,122.6541,37.8564,19.2,122.0,2022-11-13 13:15:39.627354,2022-11-13 04:11:30.000000,2022-11-13 12:13:07,under way using engine,638.081687,1332.425786,2022-11-14 16:20:49.579482,2022-11-14 14:29:52.786142,0 days 01:50:56.793340
52,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,122.6609,37.8530,19.1,121.0,2022-11-13 13:20:42.719938,2022-11-13 04:17:17.000000,2022-11-13 04:19:45,under way using engine,637.376764,1321.264630,2022-11-14 16:25:52.672066,2022-11-14 14:29:52.786142,0 days 01:55:59.885924

### 고속 (7knot 미만 포함)

#### 3. 순간 속력 이용 + 알고리즘 x  +  감속 계수 x

In [69]:
test_df_26 = pd.read_csv(f"voy_path/upper_china/processed/COSCO_FOS_VRKR6_2022_{cosco_fos_voy_number}processed.csv")
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['time_voyage_data_received'] = pd.to_datetime(test_df_26['time_voyage_data_received'])
test_df_26.drop('index', axis=1, inplace=True)
test_df_26 = test_df_26.loc[test_df_26[['longitude','latitude','timestamp']].drop_duplicates().index]
test_df_26.reset_index(inplace=True, drop=True)

In [70]:
for col in test_df_26.index:
    if col == test_df_26.index[-8]:
        break
    # 테스트 데이터
    re_sample = test_df_26.loc[col,:]
    longitude = re_sample["longitude"]
    latitude = re_sample["latitude"]
    current_point = (latitude, longitude)
    
    # 1. 순간 속력 (AIS) 
    current_speed = re_sample["speed"]
    current_position_timestamp = re_sample["timestamp"]
#     if current_speed < 7:
#         continue
    # 현재 위치에서 가장 짧은 segment 찾기
    shortest_distance = 9999
    for seg_no, seg_df in enumerate(high_speed_df_list):
        for idx in seg_df.index:
            LONGITUDE = seg_df.loc[idx, "longitude"]
            LATITUDE = seg_df.loc[idx, "latitude"]

            ais_point = (LATITUDE, LONGITUDE)
            distance = haversine(current_point, ais_point, unit="km")
            # 가장 짧은 segment 간의 거리, segment 번호, 인덱스 저장
            if distance <= shortest_distance:
                shortest_distance = distance 
                shortest_point_idx = seg_df.loc[idx, "index"]
                shortest_seg_no = seg_no
                
    # 다음 인덱스
#     optimal_point_idx = optimal_next_point(current_point, shortest_point_idx, shortest_distance, high_speed_interpolated_df)
    optimal_point_idx = high_speed_interpolated_df.query(f'index == {shortest_point_idx}').index[0] + 1
    lon_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "longitude"]
    lat_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "latitude"]
    
    optimal_point = (lat_optimal, lon_optimal)
    optimal_distance = haversine(current_point, optimal_point, unit="km")
    km_h = current_speed * 1.852
    init_duration = cal_duration(km_h, optimal_distance)
    
    
    # 가장 가까운 segment 찾기
    
    optimal_seg_no = find_segment_no(optimal_point_idx, high_speed_interpolated_df, the_number_of_seg)
    if optimal_seg_no == the_number_of_seg:
        continue
    initial_seg_df = high_speed_df_list[optimal_seg_no]
    # speed_damping_ratio는 각 segment에 맞게
#     speed_damping_ratio = current_speed / initial_seg_df["speed"].mean()
    speed_damping_ratio = 1
    km_h = current_speed * 1.852 * speed_damping_ratio
    
    
    remaining_initial_seg_df = initial_seg_df.loc[optimal_point_idx:,:]
    remaining_initial_seg_df.reset_index(inplace=True, drop=True)
    accu_distance = 0
    for idx in remaining_initial_seg_df.index:
        if idx != 0:
            LONGITUDE = remaining_initial_seg_df.loc[idx, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx, "latitude"]
            current_coord = (LATITUDE, LONGITUDE)

            LONGITUDE = remaining_initial_seg_df.loc[idx - 1, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx - 1, "latitude"]
            previous_current_coord = (LATITUDE, LONGITUDE)
            
            accu_distance += haversine(current_coord, previous_current_coord, unit="km")
            
    duration_0 = cal_duration(km_h, accu_distance)
    duration_0 = duration_0 + init_duration
    
    
        
    dura_list = []  
    for next_seg_no in range(optimal_seg_no + 1, the_number_of_seg):
        next_seg_df = high_speed_df_list[next_seg_no]
        
        seg_mean_speed = next_seg_df['speed'].mean()
#         speed_damping_ratio = current_speed / seg_mean_speed
        speed_damping_ratio = 1
        damped_mean_speed = seg_mean_speed * speed_damping_ratio
        km_h = damped_mean_speed * 1.852
        distance = reckon_point_lengths(next_seg_df)
        dura_list.append(cal_duration(km_h, distance))
    
    accu_timedelta = datetime.timedelta(seconds=0)
    for i in dura_list:
        accu_timedelta += i
    # 현재 시간 + duration = ETA
    ETA = current_position_timestamp + accu_timedelta
    test_df_26.loc[col,'ETA'] = ETA
    optimal_seg_no = 0

test_df_26['ATA'] = test_df_26.loc[test_df_26.index[-1],"timestamp"]
test_df_26['error'] = abs(test_df_26['ATA'] - test_df_26['ETA'])

experiment_no = f"6.1.2.1_seg_{the_number_of_seg}_{cosco_fos_voy_number}".replace(".","_")
result_df_dict['experiment_no'].append(experiment_no)
result_df_dict['mean_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].mean())
result_df_dict['max_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].max())

globals()[f"exp_result_df_{experiment_no}"] = test_df_26

In [71]:
print("최대:", test_df_26.loc[test_df_26.index[:-20]]["error"].max())
print("평균:", test_df_26.loc[test_df_26.index[:-20]]["error"].mean())

최대: 0 days 01:55:59.885924
평균: 0 days 00:51:07.793488160

In [72]:
test_df_26.loc[test_df_26['error'].dropna(axis=0).index].sort_values(by="error")

,vessel_name,mmsi,imo,CAPACITY,destination,eta,longitude,latitude,speed,heading,timestamp,time_position_data_received,time_voyage_data_received,navigation_info,remained_distance,estimated_fuel_consumption,ETA,ATA,error
127,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,127.2235,34.0976,18.9,80.0,2022-11-14 07:40:59.862407,2022-11-13 22:39:54,2022-11-13 06:03:53,under way using engine,175.420325,358.368072,2022-11-14 14:29:48.072802,2022-11-14 14:29:52.786142,0 days 00:00:04.713340
132,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,127.3830,34.1216,18.6,70.0,2022-11-14 08:06:14.097014,2022-11-13 23:05:42.000000,2022-11-13 06:03:53,under way using engine,161.860679,323.507171,2022-11-14 14:29:35.711722,2022-11-14 14:29:52.786142,0 days 00:00:17.074420
137,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,127.5289,34.1659,18.1,70.0,2022-11-14 08:31:28.108683,2022-11-13 23:30:54.000000,2022-11-13 06:03:53,under way using engine,148.153748,285.532243,2022-11-14 14:30:25.003449,2022-11-14 14:29:52.786142,0 days 00:00:32.217307
150,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,127.9455,34.2302,17.8,80.0,2022-11-14 09:42:08.648331,2022-11-14 00:41:37.000000,2022-11-13 06:03:53,under way using engine,114.708953,216.322056,2022-11-14 14:29:01.234260,2022-11-14 14:29:52.786142,0 days 00:00:51.551882
145,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,127.7941,34.2066,17.9,80.0,2022-11-14 09:16:54.528209,2022-11-14 00:15:54,2022-11-13 06:03:53,under way using engine,126.522328,240.332654,2022-11-14 14:28:41.340511,2022-11-14 14:29:52.786142,0 days 00:01:11.445631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,123.0270,37.6025,20.1,142.0,2022-11-13 14:16:13.292393,2022-11-13 05:12:23,2022-11-13 05:01:59,under way using engine,595.868965,1328.815541,2022-11-14 16:11:59.255820,2022-11-14 14:29:52.786142,0 days 01:42:06.469678
48,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,122.5688,37.9012,18.9,123.0,2022-11-13 12:45:22.153779,2022-11-13 03:40:41,2022-11-13 12:13:07,under way using engine,647.035778,1321.836361,2022-11-14 16:13:06.256388,2022-11-14 14:29:52.786142,0 days 01:43:13.470246
54,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,122.9137,37.7170,19.4,140.0,2022-11-13 13:56:01.931503,2022-11-13 04:50:41,2022-11-13 04:19:45,under way using engine,610.647557,1293.911531,2022-11-14 16:13:29.552211,2022-11-14 14:29:52.786142,0 days 01:43:36.766069
51,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,122.6541,37.8564,19.2,122.0,2022-11-13 13:15:39.627354,2022-11-13 04:11:30.000000,2022-11-13 12:13:07,under way using engine,638.081687,1332.425786,2022-11-14 16:20:49.579482,2022-11-14 14:29:52.786142,0 days 01:50:56.793340
52,COSCO FOS,477947700,9484302.0,4253,KRBNP,11140600,122.6609,37.8530,19.1,121.0,2022-11-13 13:20:42.719938,2022-11-13 04:17:17.000000,2022-11-13 04:19:45,under way using engine,637.376764,1321.264630,2022-11-14 16:25:52.672066,2022-11-14 14:29:52.786142,0 days 01:55:59.885924

# ETA 실험 (interpolation 10000), COSCO FOS 27항차

In [73]:
cosco_fos_voy_number = "27"

In [74]:
high_speed_interpolated_df = pd.read_csv(f"실험/upper_china_cosco_fos_high_speed_below_3_knot_{interpolation_number}_concaternated_df.csv")
high_speed_interpolated_df

         timestamp   longitude   latitude      speed
0     1.668396e+09  117.884550  38.953275  11.650000
1     1.668396e+09  117.885810  38.952988  11.708276
2     1.668396e+09  117.887070  38.952701  11.766553
3     1.668396e+09  117.888330  38.952414  11.824829
4     1.668396e+09  117.889589  38.952127  11.883105
...            ...         ...        ...        ...
9995  1.668547e+09  128.848323  34.915710  10.587933
9996  1.668547e+09  128.848054  34.916489  10.584700
9997  1.668547e+09  128.847786  34.917268  10.581466
9998  1.668547e+09  128.847518  34.918046  10.578233
9999  1.668547e+09  128.847250  34.918825  10.575000

[10000 rows x 4 columns]

In [75]:
low_speed_interpolated_df = pd.read_csv(f"실험/upper_china_cosco_fos_low_speed_below_3_knot_{interpolation_number}_concaternated_df.csv")
low_speed_interpolated_df

         timestamp   longitude   latitude      speed
0     1.668974e+09  117.979120  38.933880  10.280000
1     1.668974e+09  117.981084  38.933637  10.388327
2     1.668974e+09  117.983048  38.933394  10.496653
3     1.668974e+09  117.985012  38.933151  10.604980
4     1.668974e+09  117.986977  38.932908  10.713307
...            ...         ...        ...        ...
9995  1.669262e+09  128.856269  34.909660   8.835972
9996  1.669262e+09  128.855447  34.910475   8.826979
9997  1.669262e+09  128.854625  34.911290   8.817986
9998  1.669262e+09  128.853802  34.912105   8.808993
9999  1.669262e+09  128.852980  34.912920   8.800000

[10000 rows x 4 columns]

## segment 100

In [76]:
the_number_of_seg = 100

In [77]:
seg_length = int(len(high_speed_interpolated_df) / the_number_of_seg)

In [78]:
high_speed_df_list = []
for i in range(the_number_of_seg):
    idx = seg_length * (i + 1)
    if i == 0:
        df = high_speed_interpolated_df.loc[0:idx - 1]
        df.reset_index(inplace=True)
    else:
        df = high_speed_interpolated_df.loc[idx - seg_length:idx - 1]
        df.reset_index(inplace=True)
    high_speed_df_list.append(df)

In [79]:
# for df in high_speed_df_list:
#     d = df["speed"].mean()
#     print(d)

### 고속 (7knot 미만 제거)

#### 3. 순간 속력 이용 + 알고리즘 x  +  감속 계수 x

In [80]:
test_df_26 = pd.read_csv(f"voy_path/upper_china/processed/COSCO_FOS_VRKR6_2022_{cosco_fos_voy_number}processed.csv")
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['time_voyage_data_received'] = pd.to_datetime(test_df_26['time_voyage_data_received'])
test_df_26.drop('index', axis=1, inplace=True)
test_df_26 = test_df_26.loc[test_df_26[['longitude','latitude','timestamp']].drop_duplicates().index]
test_df_26.reset_index(inplace=True, drop=True)

In [81]:
for col in test_df_26.index:
    if col == test_df_26.index[-8]:
        break
    # 테스트 데이터
    re_sample = test_df_26.loc[col,:]
    longitude = re_sample["longitude"]
    latitude = re_sample["latitude"]
    current_point = (latitude, longitude)
    
    # 1. 순간 속력 (AIS) 
    current_speed = re_sample["speed"]
    current_position_timestamp = re_sample["timestamp"]
    if current_speed < 7:
        continue
    # 현재 위치에서 가장 짧은 segment 찾기
    shortest_distance = 9999
    for seg_no, seg_df in enumerate(high_speed_df_list):
        for idx in seg_df.index:
            LONGITUDE = seg_df.loc[idx, "longitude"]
            LATITUDE = seg_df.loc[idx, "latitude"]

            ais_point = (LATITUDE, LONGITUDE)
            distance = haversine(current_point, ais_point, unit="km")
            # 가장 짧은 segment 간의 거리, segment 번호, 인덱스 저장
            if distance <= shortest_distance:
                shortest_distance = distance 
                shortest_point_idx = seg_df.loc[idx, "index"]
                shortest_seg_no = seg_no
                
    # 다음 인덱스
#     optimal_point_idx = optimal_next_point(current_point, shortest_point_idx, shortest_distance, high_speed_interpolated_df)
    optimal_point_idx = high_speed_interpolated_df.query(f'index == {shortest_point_idx}').index[0] + 1
    lon_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "longitude"]
    lat_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "latitude"]
    
    optimal_point = (lat_optimal, lon_optimal)
    optimal_distance = haversine(current_point, optimal_point, unit="km")
    km_h = current_speed * 1.852
    init_duration = cal_duration(km_h, optimal_distance)
    
    
    # 가장 가까운 segment 찾기
    
    optimal_seg_no = find_segment_no(optimal_point_idx, high_speed_interpolated_df, the_number_of_seg)
    if optimal_seg_no == the_number_of_seg:
        continue
    initial_seg_df = high_speed_df_list[optimal_seg_no]
    # speed_damping_ratio는 각 segment에 맞게
#     speed_damping_ratio = current_speed / initial_seg_df["speed"].mean()
    speed_damping_ratio = 1
    km_h = current_speed * 1.852 * speed_damping_ratio
    
    
    remaining_initial_seg_df = initial_seg_df.loc[optimal_point_idx:,:]
    remaining_initial_seg_df.reset_index(inplace=True, drop=True)
    accu_distance = 0
    for idx in remaining_initial_seg_df.index:
        if idx != 0:
            LONGITUDE = remaining_initial_seg_df.loc[idx, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx, "latitude"]
            current_coord = (LATITUDE, LONGITUDE)

            LONGITUDE = remaining_initial_seg_df.loc[idx - 1, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx - 1, "latitude"]
            previous_current_coord = (LATITUDE, LONGITUDE)
            
            accu_distance += haversine(current_coord, previous_current_coord, unit="km")
            
    duration_0 = cal_duration(km_h, accu_distance)
    duration_0 = duration_0 + init_duration
    
    
        
    dura_list = []  
    for next_seg_no in range(optimal_seg_no + 1, the_number_of_seg):
        next_seg_df = high_speed_df_list[next_seg_no]
        
        seg_mean_speed = next_seg_df['speed'].mean()
#         speed_damping_ratio = current_speed / seg_mean_speed
        speed_damping_ratio = 1
        damped_mean_speed = seg_mean_speed * speed_damping_ratio
        km_h = damped_mean_speed * 1.852
        distance = reckon_point_lengths(next_seg_df)
        dura_list.append(cal_duration(km_h, distance))
    
    accu_timedelta = datetime.timedelta(seconds=0)
    for i in dura_list:
        accu_timedelta += i
    # 현재 시간 + duration = ETA
    ETA = current_position_timestamp + accu_timedelta
    test_df_26.loc[col,'ETA'] = ETA
    optimal_seg_no = 0

test_df_26['ATA'] = test_df_26.loc[test_df_26.index[-1],"timestamp"]
test_df_26['error'] = abs(test_df_26['ATA'] - test_df_26['ETA'])

experiment_no = f"7.1.1.1_seg_{the_number_of_seg}_{cosco_fos_voy_number}".replace(".","_")
result_df_dict['experiment_no'].append(experiment_no)
result_df_dict['mean_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].mean())
result_df_dict['max_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].max())

globals()[f"exp_result_df_{experiment_no}"] = test_df_26

In [82]:
print("최대:", test_df_26.loc[test_df_26.index[:-20]]["error"].max())
print("평균:", test_df_26.loc[test_df_26.index[:-20]]["error"].mean())

최대: 0 days 05:56:51.656572
평균: 0 days 03:21:45.037669965

In [83]:
test_df_26.loc[test_df_26['error'].dropna(axis=0).index].sort_values(by="error")

,vessel_name,mmsi,imo,CAPACITY,destination,eta,longitude,latitude,speed,heading,timestamp,time_position_data_received,time_voyage_data_received,navigation_info,remained_distance,estimated_fuel_consumption,ETA,ATA,error
216,COSCO FOS,477947700,9484302.0,4253,KRBNP,11291200,128.2968,34.2937,11.3,50.0,2022-11-29 15:35:02.250691,2022-11-29 06:34:41.000000,2022-11-29 06:13:05,under way using engine,89.079450,114.509737,2022-11-29 19:10:31.148292,2022-11-29 19:11:21.050796,0 days 00:00:49.902504
226,COSCO FOS,477947700,9484302.0,4253,KRBNP,11291200,128.4427,34.3778,11.4,50.0,2022-11-29 16:25:21.113246,2022-11-29 07:21:05.000000,2022-11-29 07:13:05,under way using engine,74.278531,95.788409,2022-11-29 19:12:17.253425,2022-11-29 19:11:21.050796,0 days 00:00:56.202629
221,COSCO FOS,477947700,9484302.0,4253,KRBNP,11291200,128.3716,34.3416,11.5,60.0,2022-11-29 16:00:11.156122,2022-11-29 06:59:21.000000,2022-11-29 06:43:08,under way using engine,80.958503,104.751225,2022-11-29 19:12:21.789042,2022-11-29 19:11:21.050796,0 days 00:01:00.738246
211,COSCO FOS,477947700,9484302.0,4253,KRBNP,11291200,128.2224,34.2461,11.1,50.0,2022-11-29 15:09:53.211946,2022-11-29 06:09:32.000000,2022-11-29 05:43:06,under way using engine,97.251188,124.274867,2022-11-29 19:09:33.667703,2022-11-29 19:11:21.050796,0 days 00:01:47.383093
240,COSCO FOS,477947700,9484302.0,4253,KRBNP,1291100,128.8127,34.6579,14.8,20.0,2022-11-29 18:00:56.347777,2022-11-29 08:58:45.000000,2022-11-29 08:43:07,under way using engine,34.664984,53.140113,2022-11-29 19:13:47.988865,2022-11-29 19:11:21.050796,0 days 00:02:26.938069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,COSCO FOS,477947700,9484302.0,4253,KRBNP,11290400,121.1319,38.4741,18.0,115.0,2022-11-28 06:11:59.395411,2022-11-27 21:07:54.000000,2022-11-27 09:07:07,under way using engine,787.831101,1507.388471,2022-11-29 13:20:51.396152,2022-11-29 19:11:21.050796,0 days 05:50:29.654644
58,COSCO FOS,477947700,9484302.0,4253,KRBNP,11290400,122.8823,37.7892,18.7,123.0,2022-11-28 11:02:14.848846,2022-11-28 02:01:08.000000,2022-11-28 02:01:07,under way using engine,616.903485,1242.015723,2022-11-29 13:19:42.469554,2022-11-29 19:11:21.050796,0 days 05:51:38.581242
1,COSCO FOS,477947700,9484302.0,4253,KRBNP,11290400,117.8137,38.9663,11.6,104.0,2022-11-27 21:06:52.733478,2022-11-27 12:05:36.000000,2022-11-27 11:43:07,under way using engine,1073.045003,1393.228085,2022-11-29 13:19:31.415693,2022-11-29 19:11:21.050796,0 days 05:51:49.635103
35,COSCO FOS,477947700,9484302.0,4253,KRBNP,11290400,120.9522,38.5189,17.5,115.0,2022-11-28 05:41:42.302133,2022-11-27 20:37:41.000000,2022-11-27 08:37:06,under way using engine,804.020588,1483.795780,2022-11-29 13:16:39.388310,2022-11-29 19:11:21.050796,0 days 05:54:41.662486
0,COSCO FOS,477947700,9484302.0,4253,KRBNP,11290400,117.7846,38.9717,9.3,102.0,2022-11-27 21:01:50.712009,2022-11-27 11:57:43.000000,2022-11-27 11:43:07,under way using engine,1075.608648,1344.942290,2022-11-29 13:14:29.394224,2022-11-29 19:11:21.050796,0 days 05:56:51.656572

### 고속 (7knot 미만 포함)

#### 3. 순간 속력 이용 + 알고리즘 x  +  감속 계수 x

In [84]:
test_df_26 = pd.read_csv(f"voy_path/upper_china/processed/COSCO_FOS_VRKR6_2022_{cosco_fos_voy_number}processed.csv")
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['timestamp'] = pd.to_datetime(test_df_26['timestamp'])
test_df_26['time_voyage_data_received'] = pd.to_datetime(test_df_26['time_voyage_data_received'])
test_df_26.drop('index', axis=1, inplace=True)
test_df_26 = test_df_26.loc[test_df_26[['longitude','latitude','timestamp']].drop_duplicates().index]
test_df_26.reset_index(inplace=True, drop=True)

In [85]:
for col in test_df_26.index:
    if col == test_df_26.index[-8]:
        break
    # 테스트 데이터
    re_sample = test_df_26.loc[col,:]
    longitude = re_sample["longitude"]
    latitude = re_sample["latitude"]
    current_point = (latitude, longitude)
    
    # 1. 순간 속력 (AIS) 
    current_speed = re_sample["speed"]
    current_position_timestamp = re_sample["timestamp"]
#     if current_speed < 7:
#         continue
    # 현재 위치에서 가장 짧은 segment 찾기
    shortest_distance = 9999
    for seg_no, seg_df in enumerate(high_speed_df_list):
        for idx in seg_df.index:
            LONGITUDE = seg_df.loc[idx, "longitude"]
            LATITUDE = seg_df.loc[idx, "latitude"]

            ais_point = (LATITUDE, LONGITUDE)
            distance = haversine(current_point, ais_point, unit="km")
            # 가장 짧은 segment 간의 거리, segment 번호, 인덱스 저장
            if distance <= shortest_distance:
                shortest_distance = distance 
                shortest_point_idx = seg_df.loc[idx, "index"]
                shortest_seg_no = seg_no
                
    # 다음 인덱스
#     optimal_point_idx = optimal_next_point(current_point, shortest_point_idx, shortest_distance, high_speed_interpolated_df)
    optimal_point_idx = high_speed_interpolated_df.query(f'index == {shortest_point_idx}').index[0] + 1
    lon_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "longitude"]
    lat_optimal = high_speed_interpolated_df.loc[optimal_point_idx, "latitude"]
    
    optimal_point = (lat_optimal, lon_optimal)
    optimal_distance = haversine(current_point, optimal_point, unit="km")
    km_h = current_speed * 1.852
    init_duration = cal_duration(km_h, optimal_distance)
    
    
    # 가장 가까운 segment 찾기
    
    optimal_seg_no = find_segment_no(optimal_point_idx, high_speed_interpolated_df, the_number_of_seg)
    if optimal_seg_no == the_number_of_seg:
        continue
    initial_seg_df = high_speed_df_list[optimal_seg_no]
    # speed_damping_ratio는 각 segment에 맞게
#     speed_damping_ratio = current_speed / initial_seg_df["speed"].mean()
    speed_damping_ratio = 1
    km_h = current_speed * 1.852 * speed_damping_ratio
    
    
    remaining_initial_seg_df = initial_seg_df.loc[optimal_point_idx:,:]
    remaining_initial_seg_df.reset_index(inplace=True, drop=True)
    accu_distance = 0
    for idx in remaining_initial_seg_df.index:
        if idx != 0:
            LONGITUDE = remaining_initial_seg_df.loc[idx, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx, "latitude"]
            current_coord = (LATITUDE, LONGITUDE)

            LONGITUDE = remaining_initial_seg_df.loc[idx - 1, "longitude"]
            LATITUDE = remaining_initial_seg_df.loc[idx - 1, "latitude"]
            previous_current_coord = (LATITUDE, LONGITUDE)
            
            accu_distance += haversine(current_coord, previous_current_coord, unit="km")
            
    duration_0 = cal_duration(km_h, accu_distance)
    duration_0 = duration_0 + init_duration
    
    
        
    dura_list = []  
    for next_seg_no in range(optimal_seg_no + 1, the_number_of_seg):
        next_seg_df = high_speed_df_list[next_seg_no]
        
        seg_mean_speed = next_seg_df['speed'].mean()
#         speed_damping_ratio = current_speed / seg_mean_speed
        speed_damping_ratio = 1
        damped_mean_speed = seg_mean_speed * speed_damping_ratio
        km_h = damped_mean_speed * 1.852
        distance = reckon_point_lengths(next_seg_df)
        dura_list.append(cal_duration(km_h, distance))
    
    accu_timedelta = datetime.timedelta(seconds=0)
    for i in dura_list:
        accu_timedelta += i
    # 현재 시간 + duration = ETA
    ETA = current_position_timestamp + accu_timedelta
    test_df_26.loc[col,'ETA'] = ETA
    optimal_seg_no = 0

test_df_26['ATA'] = test_df_26.loc[test_df_26.index[-1],"timestamp"]
test_df_26['error'] = abs(test_df_26['ATA'] - test_df_26['ETA'])

experiment_no = f"7.1.2.1_seg_{the_number_of_seg}_{cosco_fos_voy_number}".replace(".","_")
result_df_dict['experiment_no'].append(experiment_no)
result_df_dict['mean_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].mean())
result_df_dict['max_speed'].append(test_df_26.loc[test_df_26.index[:-20]]["error"].max())

globals()[f"exp_result_df_{experiment_no}"] = test_df_26

In [86]:
print("최대:", test_df_26.loc[test_df_26.index[:-20]]["error"].max())
print("평균:", test_df_26.loc[test_df_26.index[:-20]]["error"].mean())

최대: 0 days 05:56:51.656572
평균: 0 days 03:21:45.037669965

In [87]:
test_df_26.loc[test_df_26['error'].dropna(axis=0).index].sort_values(by="error")

,vessel_name,mmsi,imo,CAPACITY,destination,eta,longitude,latitude,speed,heading,timestamp,time_position_data_received,time_voyage_data_received,navigation_info,remained_distance,estimated_fuel_consumption,ETA,ATA,error
216,COSCO FOS,477947700,9484302.0,4253,KRBNP,11291200,128.2968,34.2937,11.3,50.0,2022-11-29 15:35:02.250691,2022-11-29 06:34:41.000000,2022-11-29 06:13:05,under way using engine,89.079450,114.509737,2022-11-29 19:10:31.148292,2022-11-29 19:11:21.050796,0 days 00:00:49.902504
226,COSCO FOS,477947700,9484302.0,4253,KRBNP,11291200,128.4427,34.3778,11.4,50.0,2022-11-29 16:25:21.113246,2022-11-29 07:21:05.000000,2022-11-29 07:13:05,under way using engine,74.278531,95.788409,2022-11-29 19:12:17.253425,2022-11-29 19:11:21.050796,0 days 00:00:56.202629
221,COSCO FOS,477947700,9484302.0,4253,KRBNP,11291200,128.3716,34.3416,11.5,60.0,2022-11-29 16:00:11.156122,2022-11-29 06:59:21.000000,2022-11-29 06:43:08,under way using engine,80.958503,104.751225,2022-11-29 19:12:21.789042,2022-11-29 19:11:21.050796,0 days 00:01:00.738246
211,COSCO FOS,477947700,9484302.0,4253,KRBNP,11291200,128.2224,34.2461,11.1,50.0,2022-11-29 15:09:53.211946,2022-11-29 06:09:32.000000,2022-11-29 05:43:06,under way using engine,97.251188,124.274867,2022-11-29 19:09:33.667703,2022-11-29 19:11:21.050796,0 days 00:01:47.383093
240,COSCO FOS,477947700,9484302.0,4253,KRBNP,1291100,128.8127,34.6579,14.8,20.0,2022-11-29 18:00:56.347777,2022-11-29 08:58:45.000000,2022-11-29 08:43:07,under way using engine,34.664984,53.140113,2022-11-29 19:13:47.988865,2022-11-29 19:11:21.050796,0 days 00:02:26.938069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,COSCO FOS,477947700,9484302.0,4253,KRBNP,11290400,121.1319,38.4741,18.0,115.0,2022-11-28 06:11:59.395411,2022-11-27 21:07:54.000000,2022-11-27 09:07:07,under way using engine,787.831101,1507.388471,2022-11-29 13:20:51.396152,2022-11-29 19:11:21.050796,0 days 05:50:29.654644
58,COSCO FOS,477947700,9484302.0,4253,KRBNP,11290400,122.8823,37.7892,18.7,123.0,2022-11-28 11:02:14.848846,2022-11-28 02:01:08.000000,2022-11-28 02:01:07,under way using engine,616.903485,1242.015723,2022-11-29 13:19:42.469554,2022-11-29 19:11:21.050796,0 days 05:51:38.581242
1,COSCO FOS,477947700,9484302.0,4253,KRBNP,11290400,117.8137,38.9663,11.6,104.0,2022-11-27 21:06:52.733478,2022-11-27 12:05:36.000000,2022-11-27 11:43:07,under way using engine,1073.045003,1393.228085,2022-11-29 13:19:31.415693,2022-11-29 19:11:21.050796,0 days 05:51:49.635103
35,COSCO FOS,477947700,9484302.0,4253,KRBNP,11290400,120.9522,38.5189,17.5,115.0,2022-11-28 05:41:42.302133,2022-11-27 20:37:41.000000,2022-11-27 08:37:06,under way using engine,804.020588,1483.795780,2022-11-29 13:16:39.388310,2022-11-29 19:11:21.050796,0 days 05:54:41.662486
0,COSCO FOS,477947700,9484302.0,4253,KRBNP,11290400,117.7846,38.9717,9.3,102.0,2022-11-27 21:01:50.712009,2022-11-27 11:57:43.000000,2022-11-27 11:43:07,under way using engine,1075.608648,1344.942290,2022-11-29 13:14:29.394224,2022-11-29 19:11:21.050796,0 days 05:56:51.656572

# 결과 확인

In [88]:
result_pool = pd.DataFrame(result_df_dict)
result_pool

        experiment_no                mean_speed              max_speed
0  4_1_1_1_seg_100_26 0 days 00:56:06.123337581 0 days 01:56:13.045933
1  4_1_2_1_seg_100_26 0 days 00:56:06.123337581 0 days 01:56:13.045933
2  5_1_1_1_seg_100_23 0 days 00:13:18.045748263 0 days 00:34:46.370161
3  5_1_2_1_seg_100_23 0 days 00:13:18.045748263 0 days 00:34:46.370161
4  6_1_1_1_seg_100_25 0 days 00:51:07.793488160 0 days 01:55:59.885924
5  6_1_2_1_seg_100_25 0 days 00:51:07.793488160 0 days 01:55:59.885924
6  7_1_1_1_seg_100_27 0 days 03:21:45.037669965 0 days 05:56:51.656572
7  7_1_2_1_seg_100_27 0 days 03:21:45.037669965 0 days 05:56:51.656572

In [89]:
result_pool.sort_values(by="mean_speed").head()

        experiment_no                mean_speed              max_speed
2  5_1_1_1_seg_100_23 0 days 00:13:18.045748263 0 days 00:34:46.370161
3  5_1_2_1_seg_100_23 0 days 00:13:18.045748263 0 days 00:34:46.370161
4  6_1_1_1_seg_100_25 0 days 00:51:07.793488160 0 days 01:55:59.885924
5  6_1_2_1_seg_100_25 0 days 00:51:07.793488160 0 days 01:55:59.885924
0  4_1_1_1_seg_100_26 0 days 00:56:06.123337581 0 days 01:56:13.045933

In [90]:
result_pool.to_csv(f"230126_result_pool_interpolation_{interpolation_number}_segment_100_cosco_fos_high_speed_voyages.csv", encoding="utf-8 sig", header=True, index=False)

In [91]:
for i in globals():
    if 'exp_result_df_' in i:
        print(i)
        globals()[i].to_csv(f"실험/{i}", encoding="utf-8 sig", header=True, index=False)

exp_result_df_4_1_1_1_seg_100_26
exp_result_df_4_1_2_1_seg_100_26
exp_result_df_5_1_1_1_seg_100_23
exp_result_df_5_1_2_1_seg_100_23
exp_result_df_6_1_1_1_seg_100_25
exp_result_df_6_1_2_1_seg_100_25
exp_result_df_7_1_1_1_seg_100_27
exp_result_df_7_1_2_1_seg_100_27